(() => {
  if (window.__flippersAiScannerLoadedV070) return
  window.__flippersAiScannerLoadedV070 = true
  const clean=v=>String(v||'').replace(/\s+/g,' ').trim(),text=el=>clean(el?.innerText||el?.textContent||''),unique=list=>[...new Set(list.filter(Boolean))]
  const visible=el=>{if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=='none'&&s.visibility!=='hidden'}
  function platform(){const h=location.hostname.toLowerCase();if(h.includes('facebook.com'))return'facebook';if(h.includes('ebay.com.au'))return'ebay';if(h.includes('gumtree.com.au'))return'gumtree';if(h.includes('depop.com'))return'depop';return'other'}
  function meta(name,property=false){return clean(document.querySelector(property?`meta[property="${name}"]`:`meta[name="${name}"]`)?.content)}
  function jsonLd(){const rows=[];for(const node of document.querySelectorAll('script[type="application/ld+json"]')){try{const p=JSON.parse(node.textContent||'null');if(Array.isArray(p))rows.push(...p);else if(p?.['@graph'])rows.push(...p['@graph']);else if(p)rows.push(p)}catch{}}return rows}
  function productLd(){return jsonLd().find(r=>r?.['@type']==='Product'||(Array.isArray(r?.['@type'])&&r['@type'].includes('Product')))||null}
  function numberFromPrice(v){const m=clean(v).replace(/,/g,'').match(/(?:A\$|AU\$|\$)\s*([0-9]+(?:\.\d{1,2})?)/i);if(!m)return null;const n=Number(m[1]);return Number.isFinite(n)&&n>=0&&n<10000000?n:null}
  function priceCandidates(root=document){const out=[];for(const sel of ['[itemprop="price"]','[data-testid*="price" i]','[class*="price" i]','main span','main div','article span','article div']){for(const el of root.querySelectorAll(sel)){if(!visible(el))continue;const v=text(el);if(!v||v.length>40||!/^(?:A\$|AU\$|\$)\s*[0-9][0-9,.]*(?:\s*(?:AUD|ea|each))?$/i.test(v))continue;const p=numberFromPrice(v);if(p===null)continue;const r=el.getBoundingClientRect();out.push({price:p,top:r.top,size:parseFloat(getComputedStyle(el).fontSize)||0})}if(out.length)break}return out.sort((a,b)=>(b.size-a.size)||(a.top-b.top))}
  function headings(){const list=[];for(const el of document.querySelectorAll('main h1,article h1,h1,main h2,[role="main"] [dir="auto"]')){if(!visible(el))continue;const v=text(el);if(v.length<3||v.length>220)continue;if(/marketplace|facebook|ebay|gumtree|depop|notifications|messages/i.test(v)&&v.length<40)continue;const r=el.getBoundingClientRect();list.push({value:v,size:parseFloat(getComputedStyle(el).fontSize)||0,top:r.top,tag:el.tagName})}return list.sort((a,b)=>((b.tag==='H1'?100:0)+b.size)-((a.tag==='H1'?100:0)+a.size)||a.top-b.top)}
  function exactLabel(root,rx){return [...root.querySelectorAll('span,div')].find(el=>visible(el)&&rx.test(text(el))&&text(el).length<80)}
  function nearbyAnchor(labelEl){if(!labelEl)return null;let node=labelEl;for(let depth=0;depth<6&&node;depth++,node=node.parentElement){const links=[...node.querySelectorAll('a[href]')].filter(a=>visible(a)&&text(a).length>=2&&text(a).length<100);const profile=links.find(a=>/marketplace\/profile|\/profile\.php|\/people\//i.test(a.getAttribute('href')||''));if(profile)return profile;const named=links.find(a=>{const href=a.getAttribute('href')||'';return /^https?:\/\/(?:www\.)?facebook\.com\/(?!marketplace|groups|help|share|login|watch|reel|photo)/i.test(a.href||'')&&!/\/posts\//i.test(href)});if(named)return named}return null}
  function facebookFields(){
    const main=document.querySelector('[role="main"]')||document.querySelector('main')||document.body,body=text(main),hs=headings(),prices=priceCandidates(main)
    const sellerLabel=exactLabel(main,/^(Seller information|Seller details|About the seller)$/i)
    let sellerAnchor=nearbyAnchor(sellerLabel)
    if(!sellerAnchor)sellerAnchor=[...main.querySelectorAll('a[href]')].find(a=>visible(a)&&/marketplace\/profile|\/profile\.php|\/people\//i.test(a.getAttribute('href')||'')&&text(a).length>=2&&text(a).length<100)
    let sellerName=text(sellerAnchor)
    if(!sellerName&&sellerLabel){let node=sellerLabel.parentElement;for(let i=0;i<4&&node&&!sellerName;i++,node=node.parentElement){const candidates=[...node.querySelectorAll('[dir="auto"],span')].map(text).filter(v=>v&&v.length>=2&&v.length<80&&!/seller information|seller details|message|follow|joined|rating/i.test(v));sellerName=candidates[0]||''}}
    const conditionLabel=exactLabel(main,/^Condition$/i);let condition=''
    if(conditionLabel){let node=conditionLabel.parentElement;for(let i=0;i<3&&node&&!condition;i++,node=node.parentElement){const t=text(node),m=t.match(/Condition\s*(?:·|:)?\s*(New|Used\s*[-–—]?\s*(?:Like new|Good|Fair)|Like new|Good|Fair)/i);if(m)condition=clean(m[1])}}
    if(!condition){const m=body.match(/\bCondition\s*(?:·|:)?\s*(New|Used\s*[-–—]?\s*(?:Like new|Good|Fair)|Like new|Good|Fair)\b/i);if(m)condition=clean(m[1])}
    let locationText='';for(const rx of [/(?:Listed\s+(?:\d+\s+\w+\s+ago\s+)?in\s+)([^·]{2,80})/i,/(?:Location\s*[:·]?\s*)([^·]{2,80})/i]){const m=body.match(rx);if(m){locationText=clean(m[1]);break}}
    const descLabel=exactLabel(main,/^Description$/i);let description='';if(descLabel){let node=descLabel.parentElement;for(let i=0;i<3&&node;i++,node=node.parentElement){const v=text(node).replace(/^Description\s*/i,'');if(v.length>description.length&&v.length<8000)description=v}}
    return{title:hs[0]?.value||'',price:prices[0]?.price??null,location:locationText,condition,sellerName,sellerProfileUrl:sellerAnchor?.href||'',description,conditionSource:condition?'seller':'unknown'}
  }
  function ebayFields(){const p=productLd(),offer=Array.isArray(p?.offers)?p.offers[0]:p?.offers;return{title:clean(p?.name)||text(document.querySelector('h1.x-item-title__mainTitle,h1')),price:Number(offer?.price||document.querySelector('[itemprop="price"]')?.getAttribute('content'))||priceCandidates()[0]?.price||null,condition:clean(p?.itemCondition?.name||text(document.querySelector('[data-testid="ux-labels-values__labels-content"]'))),description:clean(p?.description),conditionSource:p?.itemCondition?'seller':'unknown'}}
  function gumtreeFields(){const p=productLd(),offer=Array.isArray(p?.offers)?p.offers[0]:p?.offers,main=document.querySelector('main')||document.body,body=text(main),loc=body.match(/(?:Location|Suburb)\s*[:·]?\s*([^·]{2,80})/i);return{title:clean(p?.name)||text(document.querySelector('h1')),price:Number(offer?.price)||priceCandidates()[0]?.price||null,location:clean(loc?.[1]),condition:clean(p?.itemCondition?.name),description:clean(p?.description),conditionSource:p?.itemCondition?'seller':'unknown'}}
  function depopFields(){const p=productLd(),offer=Array.isArray(p?.offers)?p.offers[0]:p?.offers;return{title:clean(p?.name)||text(document.querySelector('h1')),price:Number(offer?.price)||priceCandidates()[0]?.price||null,condition:clean(p?.itemCondition?.name),description:clean(p?.description),conditionSource:p?.itemCondition?'seller':'unknown'}}
  function genericFields(){const p=productLd(),offer=Array.isArray(p?.offers)?p.offers[0]:p?.offers;return{title:clean(p?.name)||headings()[0]?.value||meta('og:title',true)||clean(document.title),price:Number(offer?.price)||priceCandidates()[0]?.price||null,description:clean(p?.description)||meta('og:description',true)||meta('description')}}
  function imageUrls(){const images=[];for(const img of document.images){if(!visible(img))continue;const r=img.getBoundingClientRect(),area=r.width*r.height;if(area<12000)continue;const url=img.currentSrc||img.src;if(!/^https?:/i.test(url||''))continue;const alt=clean(img.alt),penalty=/profile|avatar|logo|emoji|icon/i.test(alt)?.15:1;images.push({url,area:area*penalty})}return unique(images.sort((a,b)=>b.area-a.area).map(x=>x.url)).slice(0,14)}
  function listingId(kind){const u=location.href;if(kind==='facebook')return u.match(/\/marketplace\/item\/(\d+)/)?.[1]||'';if(kind==='ebay')return u.match(/\/itm\/(?:[^/]+\/)?(\d+)/)?.[1]||'';if(kind==='gumtree')return u.match(/\/s-ad\/[^/]+\/[^/]+\/(\d+)/)?.[1]||'';return''}
  function relevantText(){const root=document.querySelector('[role="main"]')||document.querySelector('main')||document.querySelector('article')||document.body;return text(root).slice(0,30000)}
  function confidence(f,imgs){let s=0;if(f.title)s+=30;if(f.price!=null)s+=30;if(f.description)s+=12;if(f.location)s+=10;if(f.sellerName)s+=8;if(f.condition)s+=5;if(imgs.length)s+=5;return Math.min(100,s)}
  function scan(){const kind=platform();let f=genericFields();if(kind==='facebook')f={...f,...facebookFields()};if(kind==='ebay')f={...f,...ebayFields()};if(kind==='gumtree')f={...f,...gumtreeFields()};if(kind==='depop')f={...f,...depopFields()};for(const k of['title','description','location','condition','sellerName'])f[k]=clean(f[k]);f.title=f.title.replace(/^Marketplace\s*[-–—:]\s*/i,'');const visibleText=relevantText(),imgs=imageUrls();const out={url:location.href,platform:kind,listingId:listingId(kind),title:f.title||'',askingPrice:f.price??null,location:f.location||'',condition:f.condition||'',conditionSource:f.conditionSource||'unknown',sellerName:f.sellerName||'',sellerProfileUrl:f.sellerProfileUrl||'',description:f.description||'',imageUrls:imgs,visibleText,scanConfidence:confidence(f,imgs),source:'authenticated_browser_dom',documentTitle:clean(document.title),canonicalUrl:document.querySelector('link[rel="canonical"]')?.href||location.href,ogTitle:meta('og:title',true),ogDescription:meta('og:description',true)};out.listingText=[out.description?`Description: ${out.description}`:'',out.condition?`Seller-stated condition: ${out.condition}`:'',out.location?`Location: ${out.location}`:'',out.sellerName?`Seller: ${out.sellerName}`:'',`Rendered listing page text:\n${visibleText}`].filter(Boolean).join('\n\n');return out}
  chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type!=='FLIPPERS_SCAN_PAGE')return;try{sendResponse({ok:true,data:scan()})}catch(error){sendResponse({ok:false,error:error.message||String(error)})}})
})()