import { api } from './api.js'

const $=(s,r=document)=>r.querySelector(s)
const $$=(s,r=document)=>[...r.querySelectorAll(s)]
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const money=v=>v===null||v===undefined||v===''||Number.isNaN(Number(v))?'—':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(v))
const pct=v=>v===null||v===undefined||Number.isNaN(Number(v))?'—':`${Math.round(Number(v))}%`

const runtime={busy:false,autoStarted:false,autoNextOnMutation:false,context:null,records:new Map(),quality:{attempted:0,completed:0,failed:0,totalMs:0},timer:null,progress:null}

function toast(message){$('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)}
function hasRating(c){return ['rated','analysed'].includes(c?.scan_status)||Boolean(c?.recommendation||c?.analysis?.recommendation)}
function isDeep(c){return c?.scan_status==='analysed'}
function confidence(c){const a=c?.analysis||{};return a.overall_confidence??a.valuation_confidence??a.identification_confidence??null}
function recLabel(v=''){return ({strong_buy:'Strong lead',buy:'Strong lead',negotiate:'Promising',verify_first:'Needs verification',skip:'Skip'})[v]||(v?String(v).replaceAll('_',' '):'Not rated')}
function recClass(v=''){return ['strong_buy','buy'].includes(v)?'good':['negotiate','verify_first'].includes(v)?'warn':v==='skip'?'bad':''}
function rankScore(a={}){const rec=a.recommendation;const bonus=rec==='strong_buy'?22:rec==='buy'?18:rec==='negotiate'?10:rec==='verify_first'?3:rec==='skip'?-25:0;const score=Number(a.overall_score||0),profit=Number(a.expected_profit||0),roi=Number(a.expected_roi_percent||0),conf=Number(a.overall_confidence??a.valuation_confidence??0);return Math.round((score+bonus+Math.max(-15,Math.min(20,profit/10))+Math.max(-8,Math.min(8,roi/20))+Math.max(0,Math.min(6,conf/20)))*10)/10}
function inferredCategory(c={}){return c.category_label||c.raw_capture?.category_label||c.analysis?.category||'Other'}
function complexity(c={}){let score=0;const category=inferredCategory(c);if(['Watches','Sneakers','Collectibles','Fashion'].includes(category))score+=2.2;else if(['Phones','Audio','Gaming','Computers','Cameras'].includes(category))score+=1;if(!c.title||c.title.length<6)score+=2;if(c.asking_price==null)score+=1.6;if(!c.location)score+=.5;const raw=String(c.raw_capture?.raw_text||'');if(raw.length<40)score+=1.2;if(/\b(bundle|lot|assorted|mixed|collection|replica|fake|damaged|faulty|parts|unknown|unverified)\b/i.test(`${c.title||''} ${raw}`))score+=1.8;return score}
function adaptiveBatch(records=[]){if(!records.length)return 0;const avg=records.reduce((sum,c)=>sum+complexity(c),0)/records.length,categories=new Set(records.map(inferredCategory)),missingPrice=records.filter(c=>c.asking_price==null).length/records.length,failureRate=runtime.quality.attempted?runtime.quality.failed/runtime.quality.attempted:0,avgMs=runtime.quality.completed?runtime.quality.totalMs/runtime.quality.completed:0;let n=avg>=4.2?5:avg>=3.2?6:avg>=2.3?8:avg>=1.4?10:12;if(categories.size>=4)n=Math.min(n,8);if(missingPrice>.35)n=Math.min(n,7);if(failureRate>.2)n=Math.min(n,5);else if(failureRate>.08)n=Math.min(n,7);if(avgMs>26000)n=Math.min(n,6);else if(avgMs>18000)n=Math.min(n,8);if(avg<.75&&categories.size===1&&missingPrice<.1&&failureRate<.05)n=15;return Math.max(1,Math.min(n,records.length))}
function preliminaryImageLimit(c,capture={}){const category=inferredCategory(c);if(['Watches','Sneakers','Collectibles','Fashion'].includes(category))return 2;if(!c.title||c.asking_price==null||(capture.listingText||'').length<120)return 2;if(['Phones','Audio','Gaming','Computers','Cameras'].includes(category))return 1;return 0}
function candidateIds(){return $$('.scout-candidate[data-candidate]').map(x=>x.dataset.candidate).filter(Boolean)}
async function loadRecords(){const ids=candidateIds();if(!ids.length)return[];const rows=await api.select('scout_candidates',`select=*&id=in.(${ids.join(',')})`).catch(()=>[]);runtime.records=new Map((rows||[]).map(r=>[String(r.id),r]));return rows||[]}
function cardFor(id){return $(`.scout-candidate[data-candidate="${CSS.escape(String(id))}"]`)}

function renderRecord(c){const card=cardFor(c.id);if(!card)return;const titleRow=$('.scout-candidate-title-row',card),quick=$('.scout-quick-note',card),oldMetrics=$('.scout-metrics',card),oldDepth=$('.scout-depth-label',card),actions=$('.scout-candidate-actions',card),input=$('[data-select-candidate]',card);card.classList.toggle('quality-rated',hasRating(c));card.classList.toggle('quality-deep',isDeep(c));card.dataset.qualityRank=String(c.rank_score??-999);if(!hasRating(c)){if(input){input.checked=false;input.disabled=runtime.busy}const pill=$('.scout-rec',titleRow);if(pill){pill.className='scout-rec quality-wait';pill.textContent=runtime.progress?.id===String(c.id)?'Rating…':'Next batch'}if(quick)quick.textContent=runtime.progress?.id===String(c.id)?'Reading the full listing and building a preliminary market rating…':'Captured and waiting for its high-detail first-pass rating.';oldMetrics?.remove();oldDepth?.remove();actions?.querySelector('[data-quality-start]')?.remove();return}const a=c.analysis||{},recommendation=c.recommendation||a.recommendation||'',pill=$('.scout-rec',titleRow);if(pill){pill.className=`scout-rec ${recClass(recommendation)}`;pill.textContent=recLabel(recommendation)}if(quick)quick.remove();const depth=document.createElement('div');depth.className='scout-depth-label';depth.textContent=isDeep(c)?'DEEP SCAN':'PRELIMINARY RATING';oldDepth?.replaceWith(depth)||$('.scout-meta',card)?.insertAdjacentElement('afterend',depth);const conf=confidence(c),metrics=document.createElement('div');metrics.className='scout-metrics';metrics.innerHTML=`<span class="score-metric">Score <b>${Math.round(Number(a.overall_score??c.score??0))}/100</b></span><span>Est. profit <b class="${Number(a.expected_profit??c.expected_profit??0)>=0?'positive':'negative'}">${money(a.expected_profit??c.expected_profit)}</b></span><span>Est. resale <b>${money(a.resale_mid??c.resale_mid)}</b></span><span>ROI <b>${pct(a.expected_roi_percent??c.expected_roi_percent)}</b></span>${conf==null?'':`<span>Confidence <b>${pct(conf)}</b></span>`}`;oldMetrics?.replaceWith(metrics)||depth.insertAdjacentElement('afterend',metrics);if(isDeep(c)&&recommendation!=='skip'&&actions&&!actions.querySelector('[data-quality-start]')){const start=document.createElement('button');start.className='button primary small scout-action';start.dataset.qualityStart=c.id;start.textContent='Start flip';actions.prepend(start)}}
function sortCards(){const list=$('.scout-list');if(!list)return;const cards=$$('.scout-candidate',list);cards.sort((a,b)=>Number(b.dataset.qualityRank??-999)-Number(a.dataset.qualityRank??-999));cards.forEach(card=>list.appendChild(card))}
function updateSummary(records){const rated=records.filter(hasRating),strong=rated.filter(c=>['strong_buy','buy'].includes(c.recommendation||c.analysis?.recommendation)).length,promising=rated.filter(c=>['negotiate','verify_first'].includes(c.recommendation||c.analysis?.recommendation)).length,rejected=rated.filter(c=>(c.recommendation||c.analysis?.recommendation)==='skip').length,summary=$('.scout-summary');if(summary){const cells=[...summary.children];if(cells[1]){cells[1].querySelector('span').textContent='RATED';cells[1].querySelector('strong').textContent=String(rated.length)}if(cells[3])cells[3].querySelector('strong').textContent=String(strong)}const waiting=records.filter(c=>!hasRating(c)),batch=adaptiveBatch(waiting),insight=$('.scout-insight');if(insight){if(runtime.progress){insight.classList.add('scanning');insight.innerHTML=`<strong>${runtime.progress.mode==='deep'?'Deep scanning':'Rating'} ${runtime.progress.index} of ${runtime.progress.total}…</strong><span>${esc(runtime.progress.title||'')}</span>`}else if(rated.length){insight.classList.remove('scanning');insight.innerHTML=`<strong>${strong} strong · ${promising} promising · ${rejected} skip</strong><span>${waiting.length?`${waiting.length} waiting · next adaptive batch ${batch}`:'Select the best candidates for image-enhanced deep scanning.'}</span>`}}const scanMore=$('#scanMoreResults');if(scanMore&&!runtime.busy)scanMore.textContent=waiting.length?`Scan more results · next ${batch}`:'Scan more results ↓';const checked=$$('.scout-candidate [data-select-candidate]:checked').map(input=>input.closest('.scout-candidate')?.dataset.candidate).filter(Boolean),deepEligible=checked.filter(id=>!isDeep(runtime.records.get(String(id)))).length,deepButton=$('#deepScanSelected');if(deepButton){deepButton.disabled=runtime.busy||deepEligible===0;deepButton.textContent=`Deep scan ${deepEligible} selected`}let quality=$('.scout-quality-mode');if(!quality&&summary){quality=document.createElement('section');quality.className='scout-quality-mode';summary.insertAdjacentElement('beforebegin',quality)}if(quality)quality.innerHTML='<div><span>HIGH-DETAIL SCAN</span><strong>Adaptive batch sizing · accuracy first</strong></div><small>Harder or incomplete listings automatically reduce the batch. Straightforward listings allow more at once.</small>'}

async function hydrate(){if(!$('.scout-list'))return;const records=await loadRecords();records.forEach(renderRecord);sortCards();updateSummary(records);const waiting=records.filter(c=>!hasRating(c));if(!runtime.autoStarted&&waiting.length&&!runtime.busy){runtime.autoStarted=true;const n=adaptiveBatch(waiting);rateBatch(waiting.slice(0,n),'preliminary').catch(error=>toast(error.message))}else if(runtime.autoNextOnMutation&&waiting.length&&!runtime.busy){runtime.autoNextOnMutation=false;const n=adaptiveBatch(waiting);rateBatch(waiting.slice(0,n),'preliminary').catch(error=>toast(error.message))}}
function waitForTab(tabId,timeout=16000){return new Promise((resolve,reject)=>{let done=false;const finish=error=>{if(done)return;done=true;clearTimeout(timer);chrome.tabs.onUpdated.removeListener(listener);error?reject(error):resolve()},listener=(id,info)=>{if(id===tabId&&info.status==='complete')finish()};chrome.tabs.onUpdated.addListener(listener);const timer=setTimeout(()=>finish(new Error('Timed out loading listing.')),timeout);chrome.tabs.get(tabId).then(tab=>{if(tab.status==='complete')finish()}).catch(()=>{})})}
async function sendWithRetry(tabId,message){let last;for(let i=0;i<5;i++){try{return await chrome.tabs.sendMessage(tabId,message)}catch(error){last=error;await new Promise(r=>setTimeout(r,300+i*180))}}throw last||new Error('Could not read listing tab.')}
async function captureCandidate(c){const tab=await chrome.tabs.create({url:c.source_url,active:false});try{await waitForTab(tab.id);await new Promise(r=>setTimeout(r,650));const result=await sendWithRetry(tab.id,{type:'FLIPPERS_SCAN_PAGE'});if(!result?.ok)throw new Error(result?.error||'Could not read listing.');return result.data}finally{if(tab?.id)chrome.tabs.remove(tab.id).catch(()=>{})}}
function bufferToDataUrl(buffer,mime='image/jpeg'){const bytes=new Uint8Array(buffer);let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return`data:${mime};base64,${btoa(binary)}`}
async function imageData(url){try{const response=await fetch(url,{credentials:'include',cache:'force-cache'});if(!response.ok)return null;const type=response.headers.get('content-type')||'';if(!type.startsWith('image/'))return null;const blob=await response.blob();if(blob.size>4500000)return null;return bufferToDataUrl(await blob.arrayBuffer(),type)}catch{return null}}
async function imagesFor(capture,limit){if(!limit)return[];const out=[],seen=new Set();for(const url of capture?.imageUrls||[]){if(out.length>=limit)break;if(!/^https?:/i.test(String(url||''))||seen.has(url))continue;seen.add(url);const data=await imageData(url);if(data)out.push(data)}return out}
async function context(){if(!runtime.context)runtime.context=await api.workflowState();return runtime.context}
async function analyse(c,capture,images,mode){const ctx=await context(),profile=ctx.profile||{},portfolio=ctx.portfolio||{},listingText=capture?.listingText||capture?.visibleText||c.raw_capture?.raw_text||'',price=capture?.askingPrice??c.asking_price??null,title=capture?.title||c.title||'';const data=await api.invoke('analyse-listing-v2',{listing_url:c.source_url,listing_text:listingText,platform_fields:{asking_price:price,currency:c.currency||'AUD',asking_price_verified:price!=null,asking_price_confidence:price!=null?.9:0,listing_title:title,listing_location:capture?.location||c.location||'',seller_name:capture?.sellerName||c.seller_name||''},user_overrides:{asking_price:price,currency:c.currency||'AUD'},bankroll:Number(portfolio.available_cash||0),risk_profile:profile.risk_profile||'conservative',reserve_percent:Number(profile.capital_reserve_percent??30),max_exposure_percent:Number(profile.max_single_item_exposure_percent??20),portfolio_context:portfolio,images,scan_context:{mode,instruction:mode==='deep'?'Deep Scout scan. Use full listing detail and all available visual evidence. Resolve model, condition, authenticity, inclusions and resale uncertainty as far as the evidence supports.':'Preliminary Scout rating. Produce a useful shortlist rating now from the full listing and market evidence, while staying conservative about anything that still requires deeper visual verification.'}});if(data?.error)throw new Error(data.error);return{engine_version:data.engine_version||'flippers-alpha-4-price-lock',analysis:data.analysis||{}}}
async function saveRating(c,capture,result,status){const a=result.analysis||{},body={title:capture?.title||c.title||null,asking_price:capture?.askingPrice??c.asking_price??null,location:capture?.location||c.location||null,condition:capture?.condition||c.condition||null,seller_name:capture?.sellerName||c.seller_name||null,thumbnail_url:capture?.imageUrls?.[0]||c.thumbnail_url||null,deep_capture:capture||{},analysis:{...a,engine_version:result.engine_version,scout_scan_depth:status==='analysed'?'deep':'preliminary'},scan_status:status,recommendation:a.recommendation||null,score:a.overall_score??null,resale_mid:a.resale_mid??null,expected_profit:a.expected_profit??null,expected_roi_percent:a.expected_roi_percent??null,rank_score:rankScore(a),updated_at:new Date().toISOString()};await api.update('scout_candidates',`id=eq.${c.id}`,body);Object.assign(c,body);runtime.records.set(String(c.id),c)}
async function rateBatch(records,mode){if(runtime.busy||!records.length)return;runtime.busy=true;document.body.classList.add('quality-scanning');try{for(let i=0;i<records.length;i++){const c=records[i],started=Date.now();runtime.quality.attempted++;runtime.progress={id:String(c.id),index:i+1,total:records.length,title:c.title||'Listing',mode};updateSummary([...runtime.records.values()]);renderRecord(c);toast(`${mode==='deep'?'Deep scanning':'Rating'} ${i+1} of ${records.length}…`);try{const capture=await captureCandidate(c),limit=mode==='deep'?6:preliminaryImageLimit(c,capture),images=await imagesFor(capture,limit),result=await analyse(c,capture,images,mode);await saveRating(c,capture,result,mode==='deep'?'analysed':'rated');runtime.quality.completed++;runtime.quality.totalMs+=Date.now()-started}catch(error){runtime.quality.failed++;if(mode==='deep'&&hasRating(c)){const analysis={...(c.analysis||{}),deep_scan_error:error.message};await api.update('scout_candidates',`id=eq.${c.id}`,{analysis,updated_at:new Date().toISOString()}).catch(()=>{});c.analysis=analysis}else{await api.update('scout_candidates',`id=eq.${c.id}`,{scan_status:'failed',analysis:{error:error.message,scout_scan_depth:mode},updated_at:new Date().toISOString()}).catch(()=>{});c.scan_status='failed'}}renderRecord(c);updateSummary([...runtime.records.values()])}}finally{runtime.progress=null;runtime.busy=false;document.body.classList.remove('quality-scanning');await hydrate();const rated=[...runtime.records.values()].filter(hasRating),strong=rated.filter(c=>['strong_buy','buy'].includes(c.recommendation||c.analysis?.recommendation)).length;toast(`${mode==='deep'?'Deep scan':'Ratings'} ready · ${strong} strong lead${strong===1?'':'s'}`)}}
async function deepSelected(){const ids=$$('.scout-candidate [data-select-candidate]:checked').map(input=>input.closest('.scout-candidate')?.dataset.candidate).filter(Boolean);if(!ids.length)return toast('Select at least one listing first.');await loadRecords();const records=ids.map(id=>runtime.records.get(String(id))).filter(Boolean).filter(c=>!isDeep(c));if(!records.length)return toast('Those listings are already deep-scanned.');await rateBatch(records,'deep')}
async function persistBulkSelection(ids){const selected=new Set(ids.map(String)),records=[...runtime.records.values()];await Promise.all(records.map(c=>{const on=selected.has(String(c.id)),input=$(`[data-candidate="${CSS.escape(String(c.id))}"] [data-select-candidate]`);if(input)input.checked=on;c.selected=on;return api.update('scout_candidates',`id=eq.${c.id}`,{selected:on,updated_at:new Date().toISOString()}).catch(()=>null)}));updateSummary(records)}
function platformForUrl(url=''){const host=(()=>{try{return new URL(url).hostname}catch{return''}})();if(host.includes('facebook.com'))return'facebook';if(host.includes('ebay.com.au'))return'ebay';if(host.includes('gumtree.com.au'))return'gumtree';if(host.includes('depop.com'))return'depop';return'other'}
async function waitWorkflow(opportunityId){for(let i=0;i<15;i++){const rows=await api.select('flip_workflows',`select=*&opportunity_id=eq.${encodeURIComponent(opportunityId)}&limit=1`);if(rows?.[0])return rows[0];await new Promise(r=>setTimeout(r,180))}throw new Error('Deal File saved, but workflow did not initialise.')}
async function saveAnalysis(opportunityId,c,userId){const x=c.analysis||{};if(!x.recommendation)return null;return api.insert('analyses',{opportunity_id:opportunityId,user_id:userId,engine_version:x.engine_version||'flippers-alpha-4-price-lock',identified_name:x.identified_name||c.title||'',brand:x.brand||'',model:x.model||'',variant:x.variant||'',category:x.category||'',identification_confidence:x.identification_confidence??0,resale_low:x.resale_low,resale_mid:x.resale_mid,resale_high:x.resale_high,quick_sale_value:x.quick_sale_value,sell_time_low_days:x.sell_time_low_days,sell_time_mid_days:x.sell_time_mid_days,sell_time_high_days:x.sell_time_high_days,valuation_confidence:x.valuation_confidence??0,overall_score:x.overall_score??0,overall_risk:x.overall_risk??0,recommendation:x.recommendation,recommended_offer:x.recommended_offer,max_buy:x.max_buy,break_even_sale_price:x.break_even_sale_price,expected_selling_costs:x.expected_selling_costs,expected_profit:x.expected_profit,expected_roi_percent:x.expected_roi_percent,quick_sale_profit:x.quick_sale_profit,next_action:x.next_action,questions_to_ask:x.questions_to_ask||[],inspection_checks:x.inspection_checks||[],risks:x.risks||{},assumptions:x.assumptions||[],evidence_summary:x.evidence_summary||'',raw_model_output:x,action_summary:x.action_summary||'',action_steps:x.action_steps||[],action_cautions:x.action_cautions||[],seller_message:x.seller_message||'',photo_findings:x.photo_findings||[],photo_count:0,user_overrides:{asking_price:c.asking_price},seller_confidence:x.seller_confidence??null,seller_confidence_label:x.seller_confidence_label??null,seller_confidence_reason:x.seller_confidence_reason??null,seller_signals:x.seller_signals||{},overall_confidence:x.overall_confidence??null},{single:true})}
async function startFlip(c){if(!isDeep(c))return toast('Deep scan this listing before starting the flip.');const user=await api.getUser(),capture=c.deep_capture||{},opportunity=await api.insert('opportunities',{user_id:user.id,source_platform:platformForUrl(c.source_url),source_url:c.source_url,listing_title:c.title||null,listing_text:capture.listingText||capture.visibleText||c.raw_capture?.raw_text||'',seller_asking_price:c.asking_price??null,listing_location:c.location||null,seller_name:c.seller_name||null,currency:c.currency||'AUD',status:c.recommendation==='skip'?'skipped':'watching',raw_listing:{browser_scan:true,source:'scout_session',scout_session_id:c.session_id,scout_candidate_id:c.id,listing_id:c.listing_id||null,condition:c.condition||null,scout_scan_depth:'deep',captured_at:new Date().toISOString(),canonical_url:c.source_url},updated_at:new Date().toISOString()},{single:true});if(!opportunity?.id)throw new Error('Could not create Deal File.');let workflow=await waitWorkflow(opportunity.id);if(workflow.current_step==='capture_listing'){await api.rpc('advance_flip_step',{p_workflow_id:workflow.id,p_step_key:'capture_listing',p_step_data:{captured:true,source:'scout_session',scout_candidate_id:c.id}});workflow=await waitWorkflow(opportunity.id)}workflow=(await api.select('flip_workflows',`select=*&id=eq.${workflow.id}&limit=1`))?.[0]||workflow;if(workflow.current_step==='verify_listing'&&c.title&&c.asking_price!=null){await api.update('opportunities',`id=eq.${opportunity.id}`,{user_overrides:{asking_price:c.asking_price},updated_at:new Date().toISOString()});await api.rpc('advance_flip_step',{p_workflow_id:workflow.id,p_step_key:'verify_listing',p_step_data:{asking_price:c.asking_price,verified:true,source:'scout_session'}})}await saveAnalysis(opportunity.id,c,user.id);workflow=(await api.select('flip_workflows',`select=*&id=eq.${workflow.id}&limit=1`))?.[0]||workflow;if(workflow.current_step==='analyse_deal'&&c.recommendation!=='skip')await api.rpc('advance_flip_step',{p_workflow_id:workflow.id,p_step_key:'analyse_deal',p_step_data:{analysed:true,source:'scout_session',scout_candidate_id:c.id}});await api.update('opportunities',`id=eq.${opportunity.id}`,{status:c.recommendation==='skip'?'skipped':c.recommendation==='verify_first'?'verify':c.recommendation==='negotiate'?'negotiating':'ready',updated_at:new Date().toISOString()});const next=new URL(location.href);next.searchParams.set('workflow',workflow.id);next.searchParams.set('opportunity',opportunity.id);next.searchParams.delete('view');location.href=next.toString()}

document.addEventListener('click',event=>{const deep=event.target.closest?.('#deepScanSelected');if(deep){event.preventDefault();event.stopImmediatePropagation();if(!runtime.busy)deepSelected().catch(error=>toast(error.message));return}const more=event.target.closest?.('#scanMoreResults');if(more&&!runtime.busy){const waiting=[...runtime.records.values()].filter(c=>!hasRating(c));if(waiting.length){event.preventDefault();event.stopImmediatePropagation();const n=adaptiveBatch(waiting);rateBatch(waiting.slice(0,n),'preliminary').catch(error=>toast(error.message))}else runtime.autoNextOnMutation=true;return}const start=event.target.closest?.('[data-quality-start]');if(start){event.preventDefault();event.stopImmediatePropagation();const c=runtime.records.get(String(start.dataset.qualityStart));if(!c)return;start.disabled=true;startFlip(c).catch(error=>{start.disabled=false;toast(error.message)})}},true)
document.addEventListener('flippers:bulk-select',event=>{persistBulkSelection(event.detail?.ids||[]).catch(()=>{})})
new MutationObserver(()=>{clearTimeout(runtime.timer);runtime.timer=setTimeout(()=>hydrate().catch(()=>{}),90)}).observe(document.getElementById('app'),{childList:true,subtree:true})
hydrate().catch(()=>{})
