import { api } from './api.js'

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)]
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const money=v=>v==null||v===''||Number.isNaN(Number(v))?'—':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(v))
const pct=v=>v==null||Number.isNaN(Number(v))?'—':`${Math.round(Number(v))}%`
const R={busy:false,started:false,next:false,ctx:null,rows:new Map(),stats:{a:0,c:0,f:0,ms:0},timer:null,progress:null}

function toast(m){$('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),2600)}
const rated=c=>['rated','analysed'].includes(c?.scan_status)||!!(c?.recommendation||c?.analysis?.recommendation)
const deep=c=>c?.scan_status==='analysed'
const conf=c=>{const a=c?.analysis||{};return a.overall_confidence??a.valuation_confidence??a.identification_confidence??null}
const rec=v=>({strong_buy:'Strong lead',buy:'Strong lead',negotiate:'Promising',verify_first:'Needs verification',skip:'Skip'})[v]||(v?String(v).replaceAll('_',' '):'Not rated')
const cls=v=>['strong_buy','buy'].includes(v)?'good':['negotiate','verify_first'].includes(v)?'warn':v==='skip'?'bad':''
const category=c=>c.category_label||c.raw_capture?.category_label||c.analysis?.category||'Other'

function rank(a={}){const r=a.recommendation,b=r==='strong_buy'?22:r==='buy'?18:r==='negotiate'?10:r==='verify_first'?3:r==='skip'?-25:0,s=Number(a.overall_score||0),p=Number(a.expected_profit||0),roi=Number(a.expected_roi_percent||0),cf=Number(a.overall_confidence??a.valuation_confidence??0);return Math.round((s+b+Math.max(-15,Math.min(20,p/10))+Math.max(-8,Math.min(8,roi/20))+Math.max(0,Math.min(6,cf/20)))*10)/10}
function complexity(c={}){let n=0,k=category(c),raw=String(c.raw_capture?.raw_text||'');if(['Watches','Sneakers','Collectibles','Fashion'].includes(k))n+=2.2;else if(['Phones','Audio','Gaming','Computers','Cameras'].includes(k))n+=1;if(!c.title||c.title.length<6)n+=2;if(c.asking_price==null)n+=1.6;if(!c.location)n+=.5;if(raw.length<40)n+=1.2;if(/\b(bundle|lot|assorted|mixed|collection|replica|fake|damaged|faulty|parts|unknown|unverified)\b/i.test(`${c.title||''} ${raw}`))n+=1.8;return n}
function batch(rows=[]){if(!rows.length)return 0;const av=rows.reduce((s,c)=>s+complexity(c),0)/rows.length,cats=new Set(rows.map(category)),mp=rows.filter(c=>c.asking_price==null).length/rows.length,fr=R.stats.a?R.stats.f/R.stats.a:0,ms=R.stats.c?R.stats.ms/R.stats.c:0;let n=av>=4.2?5:av>=3.2?6:av>=2.3?8:av>=1.4?10:12;if(cats.size>=4)n=Math.min(n,8);if(mp>.35)n=Math.min(n,7);if(fr>.2)n=Math.min(n,5);else if(fr>.08)n=Math.min(n,7);if(ms>26000)n=Math.min(n,6);else if(ms>18000)n=Math.min(n,8);if(av<.75&&cats.size===1&&mp<.1&&fr<.05)n=15;return Math.max(1,Math.min(n,rows.length))}
function imgLimit(c,x={}){const k=category(c);if(['Watches','Sneakers','Collectibles','Fashion'].includes(k))return 2;if(!c.title||c.asking_price==null||(x.listingText||'').length<120)return 2;if(['Phones','Audio','Gaming','Computers','Cameras'].includes(k))return 1;return 0}

async function load(){const ids=$$('.scout-candidate[data-candidate]').map(x=>x.dataset.candidate).filter(Boolean);if(!ids.length)return[];const rows=await api.select('scout_candidates',`select=*&id=in.(${ids.join(',')})`).catch(()=>[]);R.rows=new Map((rows||[]).map(x=>[String(x.id),x]));return rows||[]}
const card=id=>$(`.scout-candidate[data-candidate="${CSS.escape(String(id))}"]`)
const signature=c=>[c.scan_status,c.recommendation,c.score,c.resale_mid,c.expected_profit,c.expected_roi_percent,c.rank_score,conf(c)].join('|')
function setHTML(el,html){if(el&&el.innerHTML!==html)el.innerHTML=html}

function paint(c){
  const el=card(c.id);if(!el)return
  const input=$('[data-select-candidate]',el);if(input&&input.checked!==!!c.selected)input.checked=!!c.selected
  const sig=signature(c);if(el.dataset.qualitySig===sig&&el.dataset.qualityProgress===(R.progress?.id===String(c.id)?'1':'0'))return
  el.dataset.qualitySig=sig;el.dataset.qualityProgress=R.progress?.id===String(c.id)?'1':'0';el.dataset.qualityRank=String(c.rank_score??-999)
  el.classList.toggle('quality-rated',rated(c));el.classList.toggle('quality-deep',deep(c))
  const row=$('.scout-candidate-title-row',el),pill=$('.scout-rec',row),quick=$('.scout-quick-note',el),oldM=$('.scout-metrics',el),oldD=$('.scout-depth-label',el),actions=$('.scout-candidate-actions',el)
  if(!rated(c)){if(pill){pill.className='scout-rec quality-wait';pill.textContent=R.progress?.id===String(c.id)?'Rating…':'Next batch'}if(quick)quick.textContent=R.progress?.id===String(c.id)?'Reading the full listing and building a preliminary market rating…':'Captured and waiting for its high-detail first-pass rating.';oldM?.remove();oldD?.remove();actions?.querySelector('[data-quality-start]')?.remove();return}
  const a=c.analysis||{},rv=c.recommendation||a.recommendation||'';if(pill){pill.className=`scout-rec ${cls(rv)}`;pill.textContent=rec(rv)}quick?.remove()
  const d=document.createElement('div');d.className='scout-depth-label';d.textContent=deep(c)?'DEEP SCAN':'PRELIMINARY RATING';oldD?.replaceWith(d)||$('.scout-meta',el)?.insertAdjacentElement('afterend',d)
  const cf=conf(c),m=document.createElement('div');m.className='scout-metrics';m.innerHTML=`<span class="score-metric">Score <b>${Math.round(Number(a.overall_score??c.score??0))}/100</b></span><span>Est. profit <b class="${Number(a.expected_profit??c.expected_profit??0)>=0?'positive':'negative'}">${money(a.expected_profit??c.expected_profit)}</b></span><span>Est. resale <b>${money(a.resale_mid??c.resale_mid)}</b></span><span>ROI <b>${pct(a.expected_roi_percent??c.expected_roi_percent)}</b></span>${cf==null?'':`<span>Confidence <b>${pct(cf)}</b></span>`}`;oldM?.replaceWith(m)||d.insertAdjacentElement('afterend',m)
  if(deep(c)&&rv!=='skip'&&actions&&!actions.querySelector('[data-quality-start]')){const b=document.createElement('button');b.className='button primary small scout-action';b.dataset.qualityStart=c.id;b.textContent='Start flip';actions.prepend(b)}
}
function sortCards(){const list=$('.scout-list');if(!list)return;const cards=$$('.scout-candidate',list),sorted=[...cards].sort((a,b)=>Number(b.dataset.qualityRank??-999)-Number(a.dataset.qualityRank??-999));if(cards.map(x=>x.dataset.candidate).join('|')!==sorted.map(x=>x.dataset.candidate).join('|'))sorted.forEach(x=>list.appendChild(x))}
function summary(rows){
  const rs=rows.filter(rated),strong=rs.filter(c=>['strong_buy','buy'].includes(c.recommendation||c.analysis?.recommendation)).length,prom=rs.filter(c=>['negotiate','verify_first'].includes(c.recommendation||c.analysis?.recommendation)).length,bad=rs.filter(c=>(c.recommendation||c.analysis?.recommendation)==='skip').length,waiting=rows.filter(c=>!rated(c)),n=batch(waiting),sum=$('.scout-summary')
  if(sum){const cells=[...sum.children];if(cells[1])setHTML(cells[1],`<span>RATED</span><strong>${rs.length}</strong>`);if(cells[3])cells[3].querySelector('strong').textContent=String(strong)}
  const ins=$('.scout-insight');if(ins){const html=R.progress?`<strong>${R.progress.mode==='deep'?'Deep scanning':'Rating'} ${R.progress.i} of ${R.progress.total}…</strong><span>${esc(R.progress.title||'')}</span>`:rs.length?`<strong>${strong} strong · ${prom} promising · ${bad} skip</strong><span>${waiting.length?`${waiting.length} waiting · next adaptive batch ${n}`:'Select the best candidates for image-enhanced deep scanning.'}</span>`:'';if(html)setHTML(ins,html);ins.classList.toggle('scanning',!!R.progress)}
  const more=$('#scanMoreResults');if(more&&!R.busy)more.textContent=waiting.length?`Scan more results · next ${n}`:'Scan more results ↓'
  const checked=$$('.scout-candidate [data-select-candidate]:checked').map(x=>x.closest('.scout-candidate')?.dataset.candidate).filter(Boolean),eligible=checked.filter(id=>!deep(R.rows.get(String(id)))).length,db=$('#deepScanSelected');if(db){db.disabled=R.busy||!eligible;db.textContent=`Deep scan ${eligible} selected`}
  let q=$('.scout-quality-mode');if(!q&&sum){q=document.createElement('section');q.className='scout-quality-mode';sum.insertAdjacentElement('beforebegin',q)}if(q)setHTML(q,'<div><span>HIGH-DETAIL SCAN</span><strong>Adaptive batch sizing · accuracy first</strong></div><small>Harder or incomplete listings automatically reduce the batch. Straightforward listings allow more at once.</small>')
}
async function hydrate(){if(!$('.scout-list'))return;const rows=await load();rows.forEach(paint);sortCards();summary(rows);const waiting=rows.filter(c=>!rated(c));if(!R.started&&waiting.length&&!R.busy){R.started=true;const n=batch(waiting);rateBatch(waiting.slice(0,n),'preliminary').catch(e=>toast(e.message))}else if(R.next&&waiting.length&&!R.busy){R.next=false;const n=batch(waiting);rateBatch(waiting.slice(0,n),'preliminary').catch(e=>toast(e.message))}}

function waitTab(id,timeout=16000){return new Promise((res,rej)=>{let done=false;const finish=e=>{if(done)return;done=true;clearTimeout(t);chrome.tabs.onUpdated.removeListener(l);e?rej(e):res()},l=(tid,info)=>{if(tid===id&&info.status==='complete')finish()};chrome.tabs.onUpdated.addListener(l);const t=setTimeout(()=>finish(new Error('Timed out loading listing.')),timeout);chrome.tabs.get(id).then(x=>{if(x.status==='complete')finish()}).catch(()=>{})})}
async function send(id,msg){let last;for(let i=0;i<5;i++){try{return await chrome.tabs.sendMessage(id,msg)}catch(e){last=e;await new Promise(r=>setTimeout(r,300+i*180))}}throw last||new Error('Could not read listing tab.')}
async function capture(c){const tab=await chrome.tabs.create({url:c.source_url,active:false});try{await waitTab(tab.id);await new Promise(r=>setTimeout(r,650));const r=await send(tab.id,{type:'FLIPPERS_SCAN_PAGE'});if(!r?.ok)throw new Error(r?.error||'Could not read listing.');return r.data}finally{if(tab?.id)chrome.tabs.remove(tab.id).catch(()=>{})}}
function dataUrl(buffer,mime='image/jpeg'){const bytes=new Uint8Array(buffer);let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,Math.min(i+32768,bytes.length)));return`data:${mime};base64,${btoa(s)}`}
async function image(url){try{const r=await fetch(url,{credentials:'include',cache:'force-cache'});if(!r.ok)return null;const type=r.headers.get('content-type')||'';if(!type.startsWith('image/'))return null;const b=await r.blob();if(b.size>4500000)return null;return dataUrl(await b.arrayBuffer(),type)}catch{return null}}
async function images(x,limit){const out=[],seen=new Set();for(const url of x?.imageUrls||[]){if(out.length>=limit)break;if(!/^https?:/i.test(String(url||''))||seen.has(url))continue;seen.add(url);const d=await image(url);if(d)out.push(d)}return out}
async function ctx(){if(!R.ctx)R.ctx=await api.workflowState();return R.ctx}
async function analyse(c,x,imgs,mode){const C=await ctx(),p=C.profile||{},pf=C.portfolio||{},text=x?.listingText||x?.visibleText||c.raw_capture?.raw_text||'',price=x?.askingPrice??c.asking_price??null,title=x?.title||c.title||'',d=await api.invoke('analyse-listing-v2',{listing_url:c.source_url,listing_text:text,platform_fields:{asking_price:price,currency:c.currency||'AUD',asking_price_verified:price!=null,asking_price_confidence:price!=null?.9:0,listing_title:title,listing_location:x?.location||c.location||'',seller_name:x?.sellerName||c.seller_name||''},user_overrides:{asking_price:price,currency:c.currency||'AUD'},bankroll:Number(pf.available_cash||0),risk_profile:p.risk_profile||'conservative',reserve_percent:Number(p.capital_reserve_percent??30),max_exposure_percent:Number(p.max_single_item_exposure_percent??20),portfolio_context:pf,images:imgs,scan_context:{mode,instruction:mode==='deep'?'Deep Scout scan. Use full listing detail and all available visual evidence. Resolve model, condition, authenticity, inclusions and resale uncertainty as far as the evidence supports.':'Preliminary Scout rating. Produce a useful shortlist rating now from the full listing and market evidence, while staying conservative about anything that still requires deeper visual verification.'}});if(d?.error)throw new Error(d.error);return{engine_version:d.engine_version||'flippers-alpha-4-price-lock',analysis:d.analysis||{}}}
async function save(c,x,r,status){const a=r.analysis||{},body={title:x?.title||c.title||null,asking_price:x?.askingPrice??c.asking_price??null,location:x?.location||c.location||null,condition:x?.condition||c.condition||null,seller_name:x?.sellerName||c.seller_name||null,thumbnail_url:x?.imageUrls?.[0]||c.thumbnail_url||null,deep_capture:x||{},analysis:{...a,engine_version:r.engine_version,scout_scan_depth:status==='analysed'?'deep':'preliminary'},scan_status:status,recommendation:a.recommendation||null,score:a.overall_score??null,resale_mid:a.resale_mid??null,expected_profit:a.expected_profit??null,expected_roi_percent:a.expected_roi_percent??null,rank_score:rank(a),updated_at:new Date().toISOString()};await api.update('scout_candidates',`id=eq.${c.id}`,body);Object.assign(c,body);R.rows.set(String(c.id),c)}

async function rateBatch(rows,mode){if(R.busy||!rows.length)return;R.busy=true;try{for(let i=0;i<rows.length;i++){const c=rows[i],start=Date.now();R.stats.a++;R.progress={id:String(c.id),i:i+1,total:rows.length,title:c.title||'Listing',mode};paint(c);summary([...R.rows.values()]);toast(`${mode==='deep'?'Deep scanning':'Rating'} ${i+1} of ${rows.length}…`);try{const x=await capture(c),lim=mode==='deep'?6:imgLimit(c,x),imgs=await images(x,lim),r=await analyse(c,x,imgs,mode);await save(c,x,r,mode==='deep'?'analysed':'rated');R.stats.c++;R.stats.ms+=Date.now()-start}catch(e){R.stats.f++;if(mode==='deep'&&rated(c)){const a={...(c.analysis||{}),deep_scan_error:e.message};await api.update('scout_candidates',`id=eq.${c.id}`,{analysis:a,updated_at:new Date().toISOString()}).catch(()=>{});c.analysis=a}else{await api.update('scout_candidates',`id=eq.${c.id}`,{scan_status:'failed',analysis:{error:e.message,scout_scan_depth:mode},updated_at:new Date().toISOString()}).catch(()=>{});c.scan_status='failed'}elReset(c)}paint(c);summary([...R.rows.values()])}}finally{R.progress=null;R.busy=false;await hydrate();const rs=[...R.rows.values()].filter(rated),strong=rs.filter(c=>['strong_buy','buy'].includes(c.recommendation||c.analysis?.recommendation)).length;toast(`${mode==='deep'?'Deep scan':'Ratings'} ready · ${strong} strong lead${strong===1?'':'s'}`)}}
function elReset(c){const el=card(c.id);if(el){delete el.dataset.qualitySig;delete el.dataset.qualityProgress}}
async function deepSelected(){const ids=$$('.scout-candidate [data-select-candidate]:checked').map(x=>x.closest('.scout-candidate')?.dataset.candidate).filter(Boolean);if(!ids.length)return toast('Select at least one listing first.');await load();const rows=ids.map(id=>R.rows.get(String(id))).filter(Boolean).filter(c=>!deep(c));if(!rows.length)return toast('Those listings are already deep-scanned.');await rateBatch(rows,'deep')}
async function bulk(ids){const s=new Set(ids.map(String)),rows=[...R.rows.values()];await Promise.all(rows.map(c=>{const on=s.has(String(c.id)),i=$(`[data-candidate="${CSS.escape(String(c.id))}"] [data-select-candidate]`);if(i)i.checked=on;c.selected=on;return api.update('scout_candidates',`id=eq.${c.id}`,{selected:on,updated_at:new Date().toISOString()}).catch(()=>null)}));summary(rows)}

const platform=url=>{let h='';try{h=new URL(url).hostname}catch{}return h.includes('facebook.com')?'facebook':h.includes('ebay.com.au')?'ebay':h.includes('gumtree.com.au')?'gumtree':h.includes('depop.com')?'depop':'other'}
async function workflow(opp){for(let i=0;i<15;i++){const rows=await api.select('flip_workflows',`select=*&opportunity_id=eq.${encodeURIComponent(opp)}&limit=1`);if(rows?.[0])return rows[0];await new Promise(r=>setTimeout(r,180))}throw new Error('Deal File saved, but workflow did not initialise.')}
async function saveAnalysis(opp,c,user){const x=c.analysis||{};if(!x.recommendation)return null;return api.insert('analyses',{opportunity_id:opp,user_id:user,engine_version:x.engine_version||'flippers-alpha-4-price-lock',identified_name:x.identified_name||c.title||'',brand:x.brand||'',model:x.model||'',variant:x.variant||'',category:x.category||'',identification_confidence:x.identification_confidence??0,resale_low:x.resale_low,resale_mid:x.resale_mid,resale_high:x.resale_high,quick_sale_value:x.quick_sale_value,sell_time_low_days:x.sell_time_low_days,sell_time_mid_days:x.sell_time_mid_days,sell_time_high_days:x.sell_time_high_days,valuation_confidence:x.valuation_confidence??0,overall_score:x.overall_score??0,overall_risk:x.overall_risk??0,recommendation:x.recommendation,recommended_offer:x.recommended_offer,max_buy:x.max_buy,break_even_sale_price:x.break_even_sale_price,expected_selling_costs:x.expected_selling_costs,expected_profit:x.expected_profit,expected_roi_percent:x.expected_roi_percent,quick_sale_profit:x.quick_sale_profit,next_action:x.next_action,questions_to_ask:x.questions_to_ask||[],inspection_checks:x.inspection_checks||[],risks:x.risks||{},assumptions:x.assumptions||[],evidence_summary:x.evidence_summary||'',raw_model_output:x,action_summary:x.action_summary||'',action_steps:x.action_steps||[],action_cautions:x.action_cautions||[],seller_message:x.seller_message||'',photo_findings:x.photo_findings||[],photo_count:0,user_overrides:{asking_price:c.asking_price},seller_confidence:x.seller_confidence??null,seller_confidence_label:x.seller_confidence_label??null,seller_confidence_reason:x.seller_confidence_reason??null,seller_signals:x.seller_signals||{},overall_confidence:x.overall_confidence??null},{single:true})}
async function start(c){if(!deep(c))return toast('Deep scan this listing before starting the flip.');const u=await api.getUser(),x=c.deep_capture||{},o=await api.insert('opportunities',{user_id:u.id,source_platform:platform(c.source_url),source_url:c.source_url,listing_title:c.title||null,listing_text:x.listingText||x.visibleText||c.raw_capture?.raw_text||'',seller_asking_price:c.asking_price??null,listing_location:c.location||null,seller_name:c.seller_name||null,currency:c.currency||'AUD',status:c.recommendation==='skip'?'skipped':'watching',raw_listing:{browser_scan:true,source:'scout_session',scout_session_id:c.session_id,scout_candidate_id:c.id,listing_id:c.listing_id||null,condition:c.condition||null,scout_scan_depth:'deep',captured_at:new Date().toISOString(),canonical_url:c.source_url},updated_at:new Date().toISOString()},{single:true});if(!o?.id)throw new Error('Could not create Deal File.');let w=await workflow(o.id);if(w.current_step==='capture_listing'){await api.rpc('advance_flip_step',{p_workflow_id:w.id,p_step_key:'capture_listing',p_step_data:{captured:true,source:'scout_session',scout_candidate_id:c.id}});w=await workflow(o.id)}w=(await api.select('flip_workflows',`select=*&id=eq.${w.id}&limit=1`))?.[0]||w;if(w.current_step==='verify_listing'&&c.title&&c.asking_price!=null){await api.update('opportunities',`id=eq.${o.id}`,{user_overrides:{asking_price:c.asking_price},updated_at:new Date().toISOString()});await api.rpc('advance_flip_step',{p_workflow_id:w.id,p_step_key:'verify_listing',p_step_data:{asking_price:c.asking_price,verified:true,source:'scout_session'}})}await saveAnalysis(o.id,c,u.id);w=(await api.select('flip_workflows',`select=*&id=eq.${w.id}&limit=1`))?.[0]||w;if(w.current_step==='analyse_deal'&&c.recommendation!=='skip')await api.rpc('advance_flip_step',{p_workflow_id:w.id,p_step_key:'analyse_deal',p_step_data:{analysed:true,source:'scout_session',scout_candidate_id:c.id}});await api.update('opportunities',`id=eq.${o.id}`,{status:c.recommendation==='skip'?'skipped':c.recommendation==='verify_first'?'verify':c.recommendation==='negotiate'?'negotiating':'ready',updated_at:new Date().toISOString()});const next=new URL(location.href);next.searchParams.set('workflow',w.id);next.searchParams.set('opportunity',o.id);next.searchParams.delete('view');location.href=next.toString()}

document.addEventListener('click',e=>{const d=e.target.closest?.('#deepScanSelected');if(d){e.preventDefault();e.stopImmediatePropagation();if(!R.busy)deepSelected().catch(x=>toast(x.message));return}const more=e.target.closest?.('#scanMoreResults');if(more&&!R.busy){const waiting=[...R.rows.values()].filter(c=>!rated(c));if(waiting.length){e.preventDefault();e.stopImmediatePropagation();const n=batch(waiting);rateBatch(waiting.slice(0,n),'preliminary').catch(x=>toast(x.message))}else R.next=true;return}const b=e.target.closest?.('[data-quality-start]');if(b){e.preventDefault();e.stopImmediatePropagation();const c=R.rows.get(String(b.dataset.qualityStart));if(c){b.disabled=true;start(c).catch(x=>{b.disabled=false;toast(x.message)})}}},true)
document.addEventListener('flippers:bulk-select',e=>bulk(e.detail?.ids||[]).catch(()=>{}))

function ownMutation(m){const t=m.target;if(t.closest?.('.scout-candidate,.scout-summary,.scout-insight,.scout-quality-mode,#smartScoutOverview'))return true;if(t.classList?.contains('scout-list')){const nodes=[...m.addedNodes,...m.removedNodes].filter(n=>n.nodeType===1);return nodes.length&&nodes.every(n=>n.matches?.('.scout-candidate'))}return false}
new MutationObserver(ms=>{if(!ms.some(m=>!ownMutation(m)))return;clearTimeout(R.timer);R.timer=setTimeout(()=>hydrate().catch(()=>{}),90)}).observe(document.getElementById('app'),{childList:true,subtree:true})
hydrate().catch(()=>{})
