import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'

const supabase=createClient('https://msmpigerejpxepkylkxz.supabase.co','sb_publishable_PtTF2JaOtkV86zDg_Vf-bw_Vg0nCSpZ')
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)]
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))
let feed=null,loading=false,timer=null
function toast(message){$('.community-toast')?.remove();const el=document.createElement('div');el.className='community-toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2400)}
async function invoke(action,extra={}){const {data,error}=await supabase.functions.invoke('community-intelligence',{body:{action,...extra}});if(error||data?.error)throw new Error(data?.error||error?.message||'Intel action failed');return data}
async function load(force=false){if(feed&&!force)return feed;if(loading)return feed;loading=true;try{feed=await invoke('feed',{limit:120});return feed}finally{loading=false}}
function item(id){return (feed?.items||[]).find(x=>String(x.id)===String(id))}
function followed(id){return new Set(feed?.followed_ids||[]).has(id)}
function controls(x){const own=x.is_owner;return `<div class="v087-intel-actions"><button data-v087-intel="up" class="${x.my_vote===1?'active':''}">✓ Helpful <span>${Number(x.helpful_count||0)}</span></button><button data-v087-intel="down" class="${x.my_vote===-1?'active bad':''}">× Not helpful <span>${Number(x.not_helpful_count||0)}</span></button><button data-v087-intel="reply">Reply / thread</button><button data-v087-intel="follow" class="${followed(x.id)?'active':''}">${followed(x.id)?'Following':'Follow'}</button>${own?'<button data-v087-intel="edit">Edit</button><button data-v087-intel="delete" class="danger">Delete</button>':''}</div>`}
function decorate(){if(!feed)return;for(const card of $$('.intel-card[data-intel-card]')){const x=item(card.dataset.intelCard);if(!x)continue;card.querySelector('.v087-intel-actions')?.remove();const existing=$('.intel-actions',card);existing?.insertAdjacentHTML('beforebegin',controls(x))}}
async function vote(x,value){const next=x.my_vote===value?0:value,data=await invoke('vote',{intel_id:x.id,vote:next});Object.assign(x,data);decorate()}
async function follow(x){const want=!followed(x.id),data=await invoke('follow',{intel_id:x.id,follow:want});const s=new Set(feed.followed_ids||[]);want?s.add(x.id):s.delete(x.id);feed.followed_ids=[...s];decorate();toast(data.following?'Following this intel':'Stopped following')}
async function editItem(x){const title=prompt('Intel title',x.title||'');if(title===null)return;const summary=prompt('Intel details / summary',x.summary||'');if(summary===null)return;const product=prompt('Product / topic',x.product_name||'');if(product===null)return;const retailer=prompt('Retailer / source',x.retailer||'');if(retailer===null)return;const location=prompt('Location',x.location_text||'');if(location===null)return;const data=await invoke('edit_item',{intel_id:x.id,title,summary,product_name:product,retailer,location_text:location});Object.assign(x,data.item||{});toast('Intel updated');location.reload()}
async function deleteItem(x){if(!confirm('Delete this intel and its thread? This cannot be undone.'))return;await invoke('delete_item',{intel_id:x.id});feed.items=feed.items.filter(y=>y.id!==x.id);document.querySelector(`[data-intel-card="${CSS.escape(String(x.id))}"]`)?.remove();toast('Intel deleted')}
function reportHtml(r){const body=esc(r.body||'').replace(/\n/g,'<br>'),name=esc(r.contributor?.display_name||'Community member');return `<div class="v087-report ${r.parent_report_id?'reply':''}" data-report="${esc(r.id)}"><div><strong>${name}</strong><small>${esc(r.report_kind||'comment')}${r.updated_at&&r.updated_at!==r.created_at?' · edited':''}</small></div><p>${body||'<em>No text supplied</em>'}</p><div class="v087-report-actions"><button data-reply-report="${esc(r.id)}">Reply</button>${r.is_owner?`<button data-edit-report="${esc(r.id)}">Edit</button><button data-delete-report="${esc(r.id)}">Delete</button>`:''}</div></div>`}
async function openThread(x){const data=await invoke('thread',{intel_id:x.id}),reports=data.reports||[];$('.v087-thread-modal')?.remove();const modal=document.createElement('div');modal.className='v087-thread-modal';modal.innerHTML=`<div class="v087-thread-card"><div class="v087-thread-head"><div><span>INTEL THREAD</span><h2>${esc(x.title)}</h2></div><button data-close>×</button></div><div class="v087-thread-list">${reports.length?reports.map(reportHtml).join(''):'<p class="v087-thread-empty">No replies yet.</p>'}</div><form class="v087-reply-form"><input type="hidden" name="parent"><textarea name="details" placeholder="Add a reply, correction or useful extra detail…" required></textarea><div><small data-replying></small><button type="button" data-cancel-reply hidden>Cancel reply</button><button class="button primary">Post reply</button></div></form></div>`;document.body.appendChild(modal);$('[data-close]',modal).onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});const form=$('.v087-reply-form',modal),parent=form.elements.parent,replying=$('[data-replying]',modal),cancel=$('[data-cancel-reply]',modal);$$('[data-reply-report]',modal).forEach(b=>b.onclick=()=>{parent.value=b.dataset.replyReport;replying.textContent='Replying to a thread message';cancel.hidden=false;form.elements.details.focus()});cancel.onclick=()=>{parent.value='';replying.textContent='';cancel.hidden=true};$$('[data-edit-report]',modal).forEach(b=>b.onclick=async()=>{const r=reports.find(v=>v.id===b.dataset.editReport),text=prompt('Edit your reply/update',r?.body||'');if(text===null)return;await invoke('edit_report',{report_id:b.dataset.editReport,details:text});toast('Reply updated');modal.remove();openThread(x)});$$('[data-delete-report]',modal).forEach(b=>b.onclick=async()=>{if(!confirm('Delete this reply/update?'))return;await invoke('delete_report',{report_id:b.dataset.deleteReport});toast('Reply deleted');modal.remove();openThread(x)});form.onsubmit=async e=>{e.preventDefault();const text=String(form.elements.details.value||'').trim();if(!text)return;const button=$('button[type="submit"],button.button.primary',form);button.disabled=true;try{await invoke('submit',{intel_id:x.id,report_kind:'comment',details:text,parent_report_id:parent.value||null});toast('Reply added');modal.remove();openThread(x)}finally{button.disabled=false}}}
async function handle(e){const b=e.target.closest?.('[data-v087-intel]');if(!b)return;const card=b.closest('.intel-card[data-intel-card]'),x=item(card?.dataset.intelCard);if(!x)return;e.preventDefault();e.stopPropagation();try{if(b.dataset.v087Intel==='up')return vote(x,1);if(b.dataset.v087Intel==='down')return vote(x,-1);if(b.dataset.v087Intel==='follow')return follow(x);if(b.dataset.v087Intel==='edit')return editItem(x);if(b.dataset.v087Intel==='delete')return deleteItem(x);if(b.dataset.v087Intel==='reply')return openThread(x)}catch(err){toast(err.message)}}
document.addEventListener('click',handle,true)
async function refresh(){if(!$('.intel-card[data-intel-card]'))return;await load(true).catch(()=>null);decorate()}
new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(refresh,120)}).observe(document.getElementById('app'),{childList:true,subtree:true})
setTimeout(refresh,600)
