import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'

const supabase = createClient(
  'https://msmpigerejpxepkylkxz.supabase.co',
  'sb_publishable_PtTF2JaOtkV86zDg_Vf-bw_Vg0nCSpZ'
)

const $ = (s, root=document) => root.querySelector(s)
const $$ = (s, root=document) => [...root.querySelectorAll(s)]
const esc = (v='') => String(v).replace(/[&<>"']/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]))
const money = v => v===null||v===undefined||v===''||Number.isNaN(Number(v)) ? '—' : new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(v))
const clamp = (n,a,b) => Math.max(a,Math.min(b,n))
const appState = { settingsOpen:false, settingsTab:'profile', categories:null, profile:null, watches:null, alerts:null, prefs:null, timer:null }

const icons = {
  settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21H9.6v-.1A1.7 1.7 0 0 0 8 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 3.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H2V9.6h.1A1.7 1.7 0 0 0 3.6 8a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 8 3.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V2h4v.1A1.7 1.7 0 0 0 15 3.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 8c.15.38.36.72.66 1 .3.28.68.4 1.1.4h.1v4h-.1a1.7 1.7 0 0 0-1.76 1.6Z"/>',
  bell:'<path d="M18 8a6 6 0 1 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/>',
  edit:'<path d="M4 20h4L19 9l-4-4L4 16v4Z"/><path d="m13 7 4 4"/>',
  trash:'<path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14"/>',
  folder:'<path d="M3 6h7l2 2h9v11H3V6Z"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  filter:'<path d="M4 5h16l-6 7v6l-4 2v-8L4 5Z"/>',
  cash:'<rect x="3" y="6" width="18" height="12" rx="2"/><circle cx="12" cy="12" r="3"/>',
  shield:'<path d="M12 3 5 6v5c0 4.5 3 8 7 10 4-2 7-5.5 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/>',
  eye:'<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>',
  close:'<path d="m6 6 12 12M18 6 6 18"/>'
}
const icon=(n,s=17)=>`<svg class="ico" width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||''}</svg>`

function toast(message){ $('.platform-toast')?.remove(); const e=document.createElement('div'); e.className='platform-toast'; e.textContent=message; document.body.appendChild(e); setTimeout(()=>e.remove(),2400) }
async function userId(){ const {data}=await supabase.auth.getSession(); return data.session?.user?.id || null }
async function currentSession(){ const {data}=await supabase.auth.getSession(); return data.session }

async function loadCore(force=false){
  const uid=await userId(); if(!uid) return null
  if(!force && appState.categories && appState.profile) return appState
  const [cats,profile,watches,alerts,prefs]=await Promise.all([
    supabase.from('resale_categories').select('*').order('sort_order').order('name'),
    supabase.from('profiles').select('*').eq('id',uid).single(),
    supabase.from('community_watches').select('*').order('created_at',{ascending:false}),
    supabase.from('community_alerts').select('*, community_intel_items(*)').order('created_at',{ascending:false}).limit(100),
    supabase.from('profile_category_preferences').select('*')
  ])
  appState.categories=cats.data||[]; appState.profile=profile.data||{}; appState.watches=watches.data||[]; appState.alerts=alerts.data||[]; appState.prefs=prefs.data||[]
  return appState
}

function categoryMap(){ return new Map((appState.categories||[]).map(c=>[c.id,c])) }
function childrenOf(parent){ return (appState.categories||[]).filter(c=>(c.parent_id||null)===(parent||null)).sort((a,b)=>(a.sort_order-b.sort_order)||a.name.localeCompare(b.name)) }
function categoryPath(id){ const map=categoryMap(); const out=[]; let c=map.get(id),guard=0; while(c&&guard++<30){ out.unshift(c.name); c=c.parent_id?map.get(c.parent_id):null } return out.join(' / ') }
function categoryMatches(child,parent){ if(!parent) return true; const map=categoryMap(); let id=child,guard=0; while(id&&guard++<30){ if(id===parent)return true; id=map.get(id)?.parent_id||null } return false }
function categoryOptions(selected='',allowBlank=true){
  const rows=[]
  const walk=(parent,depth)=>childrenOf(parent).forEach(c=>{ rows.push(`<option value="${c.id}" ${c.id===selected?'selected':''}>${'— '.repeat(depth)}${esc(c.name)}${c.owner_user_id?' · custom':''}</option>`); walk(c.id,depth+1) })
  walk(null,0); return `${allowBlank?'<option value="">Uncategorised</option>':''}${rows.join('')}`
}
function tagsArray(v){ return String(v||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,30) }

function modal(inner,wide=false){
  closeModal(); const wrap=document.createElement('div'); wrap.className='platform-modal'; wrap.innerHTML=`<div class="platform-modal-bg"></div><div class="platform-modal-card ${wide?'wide':''}"><button class="platform-modal-x" aria-label="Close">${icon('close',19)}</button>${inner}</div>`; document.body.appendChild(wrap); $('.platform-modal-bg',wrap).onclick=closeModal; $('.platform-modal-x',wrap).onclick=closeModal; return wrap
}
function closeModal(){ $('.platform-modal')?.remove() }
function confirmDestructive(title,copy,word,onConfirm){
  const wrap=modal(`<div class="platform-modal-head danger"><span class="eyebrow">DESTRUCTIVE ACTION</span><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><form id="dangerConfirm" class="form-stack"><label>Type <strong>${esc(word)}</strong> to confirm<input name="confirm" autocomplete="off" required></label><button class="button danger-button">Confirm reset</button></form>`)
  $('#dangerConfirm',wrap).onsubmit=async e=>{e.preventDefault(); if(String(new FormData(e.currentTarget).get('confirm')).trim()!==word)return toast(`Type ${word} exactly`); const b=$('button',e.currentTarget);b.disabled=true;try{await onConfirm();closeModal();toast('Done');location.reload()}catch(err){toast(err.message);b.disabled=false}}
}

function pageKind(){ return $('.page-head .eyebrow')?.textContent?.trim().toUpperCase() || '' }

async function injectChrome(){
  if(!$('.topbar') || !(await userId())) return
  await loadCore()
  const pop=$('#accountPopover')
  if(pop && !$('#platformSettingsButton')){
    const email=$('.account-email',pop)
    if(email && !$('.account-name',pop)) email.insertAdjacentHTML('beforebegin',`<div class="account-name">${esc(appState.profile?.display_name||'Your account')}</div>`)
    const signout=$('#logoutButton',pop)
    const b=document.createElement('button'); b.id='platformSettingsButton'; b.className='popover-action'; b.innerHTML=`${icon('settings')} Profile & settings`; b.onclick=e=>{e.stopPropagation();appState.settingsOpen=true;renderSettings()}; signout?.before(b)
  }
  const account=$('.account-wrap')
  if(account && !$('#platformBell')){
    const unread=(appState.alerts||[]).filter(a=>!a.read_at).length
    const b=document.createElement('button'); b.id='platformBell'; b.className='notification-button'; b.innerHTML=`${icon('bell',19)}${unread?`<span>${unread>99?'99+':unread}</span>`:''}`; b.setAttribute('aria-label','Alerts'); b.onclick=()=>openAlerts(); account.before(b)
  }
}

async function openAlerts(){
  await loadCore(true); const alerts=appState.alerts||[]
  const wrap=modal(`<div class="platform-modal-head"><span class="eyebrow">INTEL ALERTS</span><h2>Alerts</h2><div class="modal-actions"><button class="text-button" id="markAlertsRead">Mark all read</button></div></div><div class="alert-list">${alerts.length?alerts.map(a=>{const i=a.community_intel_items||{};return `<div class="alert-row ${a.read_at?'':'unread'}"><div><span class="alert-dot"></span><strong>${esc(i.title||'Community Intel update')}</strong><small>${esc(a.reason||'Matched one of your watches')}</small></div><span>${Math.round(Number(i.confidence_score||0))}%</span></div>`}).join(''):'<div class="platform-empty">No alerts yet. Create a watch and FlippersAI will surface matching community intelligence here.</div>'}</div><div class="modal-footer"><button class="button secondary" id="manageWatchesFromAlerts">Manage watches</button></div>`,true)
  $('#markAlertsRead',wrap)?.addEventListener('click',async()=>{const uid=await userId();await supabase.from('community_alerts').update({read_at:new Date().toISOString()}).eq('user_id',uid).is('read_at',null);appState.alerts=null;closeModal();toast('Alerts marked read');schedule()})
  $('#manageWatchesFromAlerts',wrap)?.addEventListener('click',()=>{closeModal();appState.settingsOpen=true;appState.settingsTab='watches';renderSettings()})
}

async function enhanceDeals(){
  if(pageKind()!=='DEALS'||$('#platformDealTools'))return
  await loadCore(); const {data:opps}=await supabase.from('opportunities').select('*').order('updated_at',{ascending:false})
  const head=$('.page-head'); if(!head)return
  head.insertAdjacentHTML('afterend',`<div class="platform-toolbar" id="platformDealTools"><div class="platform-search"><input id="dealSearch" placeholder="Search deals"></div><select id="dealCategory"><option value="">All categories</option>${categoryOptions('',false)}</select><button class="button secondary" id="resetDeals">Reset deals</button></div>`)
  const rows=$$('.opportunity-row')
  rows.forEach((row,idx)=>{const o=(opps||[])[idx];if(!o)return;row.dataset.recordId=o.id; const main=$('.opportunity-main',row); if(o.category_id)main?.insertAdjacentHTML('beforeend',`<small class="record-path">${icon('folder',12)} ${esc(categoryPath(o.category_id))}</small>`); const actions=document.createElement('div');actions.className='record-actions';actions.innerHTML=`<button data-record-edit="${o.id}" aria-label="Edit">${icon('edit')}</button><button data-record-delete="${o.id}" aria-label="Delete">${icon('trash')}</button>`;row.appendChild(actions)})
  const filter=()=>{const q=$('#dealSearch')?.value.toLowerCase().trim()||'',cat=$('#dealCategory')?.value||''; rows.forEach((r,idx)=>{const o=(opps||[])[idx];const hay=[o?.listing_title,o?.source_platform,o?.listing_location,o?.tags?.join(' ')].join(' ').toLowerCase();r.style.display=(!q||hay.includes(q))&&(!cat||categoryMatches(o?.category_id,cat))?'':'none'})}
  $('#dealSearch')?.addEventListener('input',filter);$('#dealCategory')?.addEventListener('change',filter)
  $$('[data-record-edit]').forEach(b=>b.onclick=()=>editDeal((opps||[]).find(o=>o.id===b.dataset.recordEdit)))
  $$('[data-record-delete]').forEach(b=>b.onclick=()=>confirmDestructive('Delete this deal?','This removes the Deal File and its analysis history. Purchased inventory is kept.','DELETE',async()=>{const {error}=await supabase.rpc('delete_deal',{p_opportunity_id:b.dataset.recordDelete});if(error)throw error}))
  $('#resetDeals')?.addEventListener('click',()=>confirmDestructive('Reset all deals?','Every Deal File and analysis will be removed. Inventory already purchased is kept.','RESET DEALS',async()=>{const {error}=await supabase.rpc('reset_user_section',{p_section:'deals',p_starting_balance:0});if(error)throw error}))
}

async function editDeal(o){ if(!o)return;await loadCore();const wrap=modal(`<div class="platform-modal-head"><span class="eyebrow">EDIT DEAL</span><h2>${esc(o.listing_title||'Deal')}</h2></div><form id="editDealForm" class="form-stack"><label>Title<input name="title" value="${esc(o.listing_title||'')}"></label><div class="form-grid"><label>Asking price<input name="price" type="number" min="0" step="0.01" value="${o.seller_asking_price??''}"></label><label>Location<input name="location" value="${esc(o.listing_location||'')}"></label></div><label>Category<select name="category_id">${categoryOptions(o.category_id||'')}</select></label><label>Tags<input name="tags" value="${esc((o.tags||[]).join(', '))}" placeholder="limited edition, sealed, local"></label><label>Listing URL<input name="url" value="${esc(o.source_url||'')}"></label><label>Listing notes<textarea name="text">${esc(o.listing_text||'')}</textarea></label><button class="button primary">Save changes</button></form>`,true);$('#editDealForm',wrap).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('opportunities').update({listing_title:f.get('title')||null,seller_asking_price:f.get('price')===''?null:Number(f.get('price')),listing_location:f.get('location')||null,source_url:f.get('url')||null,listing_text:f.get('text')||null,category_id:f.get('category_id')||null,tags:tagsArray(f.get('tags')),updated_at:new Date().toISOString()}).eq('id',o.id);if(error)return toast(error.message);closeModal();toast('Deal updated');location.reload()}}

async function enhanceInventory(){
  if(pageKind()!=='INVENTORY'||$('#platformInventoryTools'))return
  await loadCore();const {data:items}=await supabase.from('inventory_items').select('*').order('updated_at',{ascending:false});const head=$('.page-head');if(!head)return
  head.insertAdjacentHTML('afterend',`<div class="platform-toolbar" id="platformInventoryTools"><div class="platform-search"><input id="inventorySearch" placeholder="Search inventory"></div><select id="inventoryCategory"><option value="">All categories</option>${categoryOptions('',false)}</select><button class="button secondary" id="resetInventory">Reset inventory</button></div>`)
  const rows=$$('.inventory-row');rows.forEach((row,idx)=>{const i=(items||[])[idx];if(!i)return;row.dataset.recordId=i.id;const copy=$('.inventory-copy',row);if(i.category_id)copy?.insertAdjacentHTML('beforeend',`<small class="record-path">${icon('folder',12)} ${esc(categoryPath(i.category_id))}</small>`);const actions=document.createElement('div');actions.className='record-actions';actions.innerHTML=`<button data-inventory-edit="${i.id}" aria-label="Edit">${icon('edit')}</button><button data-inventory-delete="${i.id}" aria-label="Delete">${icon('trash')}</button>`;row.appendChild(actions)})
  const filter=()=>{const q=$('#inventorySearch')?.value.toLowerCase().trim()||'',cat=$('#inventoryCategory')?.value||'';rows.forEach((r,idx)=>{const i=(items||[])[idx];const hay=[i?.title,i?.category,i?.notes,i?.tags?.join(' ')].join(' ').toLowerCase();r.style.display=(!q||hay.includes(q))&&(!cat||categoryMatches(i?.category_id,cat))?'':'none'})};$('#inventorySearch')?.addEventListener('input',filter);$('#inventoryCategory')?.addEventListener('change',filter)
  $$('[data-inventory-edit]').forEach(b=>b.onclick=()=>editInventory((items||[]).find(i=>i.id===b.dataset.inventoryEdit)))
  $$('[data-inventory-delete]').forEach(b=>b.onclick=()=>confirmDestructive('Delete this inventory item?','The item, linked listing/sale records and its item-specific finance entries will be removed.','DELETE',async()=>{const {error}=await supabase.rpc('delete_inventory_record',{p_inventory_id:b.dataset.inventoryDelete});if(error)throw error}))
  $('#resetInventory')?.addEventListener('click',()=>confirmDestructive('Reset inventory?','All inventory, item sale records and item-specific finance entries will be removed.','RESET INVENTORY',async()=>{const {error}=await supabase.rpc('reset_user_section',{p_section:'inventory',p_starting_balance:0});if(error)throw error}))
}

async function editInventory(i){if(!i)return;await loadCore();const statuses=['purchased','preparing','ready_to_list','listed','sale_agreed','packed','shipped','delivered','sold','returned','written_off'];const wrap=modal(`<div class="platform-modal-head"><span class="eyebrow">EDIT INVENTORY</span><h2>${esc(i.title||'Inventory item')}</h2></div><form id="editInventoryForm" class="form-stack"><label>Item title<input name="title" value="${esc(i.title||'')}"></label><div class="form-grid"><label>Purchase price<input name="price" type="number" min="0" step="0.01" value="${i.purchase_price??0}"></label><label>Acquisition costs<input name="costs" type="number" min="0" step="0.01" value="${i.acquisition_costs??0}"></label></div><div class="form-grid"><label>Status<select name="status">${statuses.map(s=>`<option value="${s}" ${s===i.status?'selected':''}>${esc(s.replaceAll('_',' '))}</option>`).join('')}</select></label><label>Category<select name="category_id">${categoryOptions(i.category_id||'')}</select></label></div><label>Tags<input name="tags" value="${esc((i.tags||[]).join(', '))}"></label><label>Notes<textarea name="notes">${esc(i.notes||'')}</textarea></label><div class="platform-callout">Changing purchase price or acquisition costs also updates the linked finance entries so your capital stays consistent.</div><button class="button primary">Save changes</button></form>`,true);$('#editInventoryForm',wrap).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('update_inventory_record',{p_inventory_id:i.id,p_title:f.get('title'),p_category_id:f.get('category_id')||null,p_tags:tagsArray(f.get('tags')),p_status:f.get('status'),p_purchase_price:Number(f.get('price')||0),p_acquisition_costs:Number(f.get('costs')||0),p_notes:f.get('notes')||null});if(error)return toast(error.message);closeModal();toast('Inventory updated');location.reload()}}

async function enhanceFinance(){
  if(pageKind()!=='FINANCES'||$('#platformFinanceTools'))return
  const head=$('.page-head');if(!head)return;const {data:tx}=await supabase.from('transactions').select('*').order('occurred_at',{ascending:false}).limit(150)
  head.insertAdjacentHTML('afterend',`<div class="finance-command" id="platformFinanceTools"><button class="finance-action" data-finance="add">${icon('plus')}<span><strong>Add funds</strong><small>Increase available cash</small></span></button><button class="finance-action" data-finance="remove">${icon('cash')}<span><strong>Remove funds</strong><small>Withdraw from bankroll</small></span></button><button class="finance-action" data-finance="set">${icon('edit')}<span><strong>Set balance</strong><small>Correct current cash</small></span></button><button class="finance-action danger-lite" data-finance="reset">${icon('trash')}<span><strong>Reset finances</strong><small>Start the ledger again</small></span></button></div>`)
  $$('[data-finance]').forEach(b=>b.onclick=()=>financeAction(b.dataset.finance))
  $$('.transaction-row').forEach((row,idx)=>{const t=(tx||[])[idx];if(!t)return;if(t.metadata?.manual||['funds_added','funds_removed','adjustment'].includes(t.transaction_type)){const b=document.createElement('button');b.className='transaction-edit';b.innerHTML=icon('edit',14);b.title='Edit transaction';b.onclick=()=>editTransaction(t);row.appendChild(b)}})
}

function financeAction(kind){
  if(kind==='reset')return confirmDestructive('Reset finance ledger?','All finance transactions will be deleted. Deals and inventory remain. You can enter a new starting balance after reset.','RESET FINANCES',async()=>{const {error}=await supabase.rpc('reset_user_section',{p_section:'finances',p_starting_balance:0});if(error)throw error})
  const title=kind==='add'?'Add funds':kind==='remove'?'Remove funds':'Set available cash';const wrap=modal(`<div class="platform-modal-head"><span class="eyebrow">FINANCES</span><h2>${title}</h2></div><form id="financeActionForm" class="form-stack"><label>${kind==='set'?'New balance':'Amount'}<input name="amount" type="number" min="0" step="0.01" required></label><label>Note<input name="description" placeholder="${kind==='set'?'Balance correction':'Optional note'}"></label><button class="button primary">Save</button></form>`);$('#financeActionForm',wrap).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),amt=Number(f.get('amount')||0);const call=kind==='set'?supabase.rpc('set_cash_balance',{p_balance:amt,p_description:f.get('description')||'Balance adjustment'}):supabase.rpc('adjust_funds',{p_amount:kind==='remove'?-amt:amt,p_description:f.get('description')||null});const {error}=await call;if(error)return toast(error.message);closeModal();toast('Finances updated');location.reload()}
}
function editTransaction(t){const wrap=modal(`<div class="platform-modal-head"><span class="eyebrow">EDIT FINANCE ENTRY</span><h2>${esc(t.description||'Transaction')}</h2></div><form id="editTxForm" class="form-stack"><label>Cash change <small>Positive adds cash; negative removes it.</small><input name="delta" type="number" step="0.01" value="${Number(t.cash_delta||0)}"></label><label>Description<input name="description" value="${esc(t.description||'')}"></label><button class="button primary">Save entry</button></form>`);$('#editTxForm',wrap).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.rpc('edit_manual_transaction',{p_transaction_id:t.id,p_cash_delta:Number(f.get('delta')||0),p_description:f.get('description')||''});if(error)return toast(error.message);closeModal();toast('Entry updated');location.reload()}}

function watchMatches(w,i){const text=[i.title,i.product_name,i.summary,i.retailer,i.location_text,i.category,(i.tags||[]).join(' ')].join(' ').toLowerCase();return i.status!=='expired'&&Number(i.confidence_score||0)>=Number(w.min_confidence||0)&&(!w.confirmed_only||i.status==='confirmed')&&(!(w.intel_types||[]).length||(w.intel_types||[]).includes(i.intel_type))&&(!w.category_id||categoryMatches(i.category_id,w.category_id))&&(!w.retailer||String(i.retailer||'').toLowerCase().includes(w.retailer.toLowerCase()))&&(!w.location_text||String(i.location_text||'').toLowerCase().includes(w.location_text.toLowerCase()))&&(!w.query||text.includes(w.query.toLowerCase()))}
async function enhanceIntel(){
  if(!$('.community-head')||$('#platformIntelPersonal'))return
  await loadCore();const {data:items}=await supabase.from('community_intel_items').select('*').order('last_activity_at',{ascending:false}).limit(150);const prefs=new Set((appState.prefs||[]).map(p=>p.category_id));const home=(appState.profile?.home_area||'').toLowerCase();const watches=appState.watches||[]
  const score=i=>{let s=Number(i.confidence_score||0)/2;if(i.status==='confirmed')s+=20;if(home&&String(i.location_text||'').toLowerCase().includes(home))s+=20;if([...prefs].some(p=>categoryMatches(i.category_id,p)))s+=25;if(watches.some(w=>watchMatches(w,i)))s+=45;return s}
  const recommended=(items||[]).filter(i=>i.status!=='expired').sort((a,b)=>score(b)-score(a)).slice(0,3)
  const head=$('.community-head');head.insertAdjacentHTML('afterend',`<section class="personal-intel" id="platformIntelPersonal"><div class="personal-intel-head"><div><span class="eyebrow">FOR YOU</span><h2>Relevant intelligence</h2></div><div><button class="button secondary" id="newWatch">${icon('bell')} Create watch</button><button class="button secondary" id="manageIntelAlerts">Alerts</button></div></div><div class="personal-intel-grid">${recommended.length?recommended.map(i=>`<button data-jump-intel="${i.id}" class="personal-intel-card"><span>${esc(i.status.replaceAll('_',' '))} · ${Math.round(Number(i.confidence_score||0))}%</span><strong>${esc(i.title)}</strong><small>${esc([i.retailer,i.location_text].filter(Boolean).join(' · ')||i.category||'Community Intel')}</small></button>`).join(''):'<div class="platform-empty">Create watches or choose category interests and this section becomes your personalised opportunity feed.</div>'}</div></section>`)
  $('.intel-type-chips')?.insertAdjacentHTML('afterend',`<div class="intel-advanced-filters"><span>${icon('filter',15)} Refine</span><select id="intelCategoryFilter"><option value="">All categories</option>${categoryOptions('',false)}</select><input id="intelLocationFilter" placeholder="Location"><select id="intelConfidenceFilter"><option value="0">Any confidence</option><option value="60">60%+</option><option value="75">75%+</option><option value="90">90%+</option></select></div>`)
  const apply=()=>{const cat=$('#intelCategoryFilter')?.value||'',loc=($('#intelLocationFilter')?.value||'').toLowerCase().trim(),conf=Number($('#intelConfidenceFilter')?.value||0);$$('[data-intel-card]').forEach(card=>{const i=(items||[]).find(x=>x.id===card.dataset.intelCard);if(!i)return;card.style.display=(!cat||categoryMatches(i.category_id,cat))&&(!loc||String(i.location_text||'').toLowerCase().includes(loc))&&Number(i.confidence_score||0)>=conf?'':'none'})};$('#intelCategoryFilter')?.addEventListener('change',apply);$('#intelLocationFilter')?.addEventListener('input',apply);$('#intelConfidenceFilter')?.addEventListener('change',apply)
  $$('[data-jump-intel]').forEach(b=>b.onclick=()=>document.querySelector(`[data-intel-card="${b.dataset.jumpIntel}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}));$('#newWatch')?.addEventListener('click',()=>openWatch());$('#manageIntelAlerts')?.addEventListener('click',openAlerts)
  const shareFormObserver=new MutationObserver(()=>{const f=$('#shareIntelForm');if(f&&!$('#platformShareCategory',f)){const old=$('input[name="category"]',f);if(old){old.closest('label').innerHTML=`Category<select name="category" id="platformShareCategory"><option value="">Choose category</option>${(appState.categories||[]).map(c=>`<option value="${esc(c.name)}">${esc(categoryPath(c.id))}</option>`).join('')}</select>`}}});shareFormObserver.observe(document.body,{childList:true,subtree:true});setTimeout(()=>shareFormObserver.disconnect(),120000)
}

async function openWatch(existing=null){await loadCore();const w=existing||{};const wrap=modal(`<div class="platform-modal-head"><span class="eyebrow">PERSONALISED INTEL</span><h2>${existing?'Edit watch':'Create a watch'}</h2><p>FlippersAI will surface matching community intelligence without making you monitor a feed.</p></div><form id="watchForm" class="form-stack"><label>Watch name<input name="name" value="${esc(w.name||'')}" placeholder="Melbourne Pokémon restocks" required></label><div class="form-grid"><label>Keywords<input name="query" value="${esc(w.query||'')}" placeholder="151, Prismatic Evolutions"></label><label>Category<select name="category_id">${categoryOptions(w.category_id||'')}</select></label></div><div class="form-grid"><label>Retailer<input name="retailer" value="${esc(w.retailer||'')}"></label><label>Location<input name="location" value="${esc(w.location_text||appState.profile?.home_area||'')}"></label></div><div class="form-grid"><label>Minimum confidence<select name="confidence">${[0,50,60,75,90].map(v=>`<option value="${v}" ${Number(w.min_confidence||0)===v?'selected':''}>${v?`${v}%+`:'Any'}</option>`).join('')}</select></label><label class="checkbox-row"><input type="checkbox" name="confirmed" ${w.confirmed_only?'checked':''}><span>Confirmed only</span></label></div><label>Intel types<div class="watch-types">${['restock','release','deal','price','availability','strategy'].map(t=>`<label><input type="checkbox" name="type" value="${t}" ${(w.intel_types||[]).includes(t)?'checked':''}><span>${t}</span></label>`).join('')}</div></label><button class="button primary">Save watch</button></form>`);$('#watchForm',wrap).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),uid=await userId(),row={user_id:uid,name:f.get('name'),query:f.get('query')||null,category_id:f.get('category_id')||null,retailer:f.get('retailer')||null,location_text:f.get('location')||null,intel_types:f.getAll('type'),min_confidence:Number(f.get('confidence')||0),confirmed_only:f.get('confirmed')==='on',enabled:true,updated_at:new Date().toISOString()};let result;if(existing)result=await supabase.from('community_watches').update(row).eq('id',existing.id).select().single();else result=await supabase.from('community_watches').insert(row).select().single();if(result.error)return toast(result.error.message);await supabase.rpc('refresh_watch_alerts',{p_watch_id:result.data.id});appState.watches=null;appState.alerts=null;closeModal();toast('Watch saved');location.reload()}}

async function renderSettings(){
  await loadCore(true);const mount=$('.content');if(!mount)return;$$('.desktop-nav-item,.mobile-nav-item,.community-nav').forEach(x=>x.classList.remove('active'))
  mount.innerHTML=`<section class="settings-shell"><aside class="settings-nav"><div><span class="eyebrow">ACCOUNT</span><h1>Settings</h1></div>${[['profile','Profile'],['categories','Categories'],['interests','Interests'],['watches','Watches & alerts'],['data','Data & resets']].map(([v,l])=>`<button data-setting-tab="${v}" class="${appState.settingsTab===v?'active':''}">${l}</button>`).join('')}</aside><div class="settings-main" id="settingsMain"></div></section>`
  $$('[data-setting-tab]').forEach(b=>b.onclick=()=>{appState.settingsTab=b.dataset.settingTab;renderSettings()});renderSettingsTab()
}
function renderSettingsTab(){const box=$('#settingsMain');if(!box)return;const p=appState.profile||{};if(appState.settingsTab==='profile'){
  currentSession().then(session=>{box.innerHTML=`<div class="settings-section-head"><span class="eyebrow">PROFILE</span><h2>Your FlippersAI identity</h2><p>Use your name in the product instead of your email, and set the location used for personalised Intel.</p></div><form id="profileForm" class="settings-card form-stack"><div class="form-grid"><label>Display name<input name="name" value="${esc(p.display_name||'')}" placeholder="Benjamin"></label><label>Email<input value="${esc(session?.user?.email||'')}" disabled></label></div><label>Home area<input name="home" value="${esc(p.home_area||'')}" placeholder="Melbourne, VIC"></label><label>Short profile note<textarea name="bio" placeholder="Optional">${esc(p.profile_bio||'')}</textarea></label><div class="form-grid"><label>Monthly profit goal<input name="goal" type="number" min="0" step="50" value="${p.monthly_profit_goal??''}"></label><label>Guidance<select name="guidance"><option value="teach" ${p.guidance_level==='teach'?'selected':''}>Teach me</option><option value="assist" ${p.guidance_level==='assist'?'selected':''}>Assist me</option><option value="fast" ${p.guidance_level==='fast'?'selected':''}>Move fast</option></select></label></div><button class="button primary">Save profile</button></form>`;$('#profileForm').onsubmit=saveProfile})
 }else if(appState.settingsTab==='categories')renderCategories(box);else if(appState.settingsTab==='interests')renderInterests(box);else if(appState.settingsTab==='watches')renderWatches(box);else renderData(box)}
async function saveProfile(e){e.preventDefault();const f=new FormData(e.currentTarget),uid=await userId();const {error}=await supabase.from('profiles').update({display_name:f.get('name')||null,home_area:f.get('home')||null,profile_bio:f.get('bio')||null,monthly_profit_goal:f.get('goal')?Number(f.get('goal')):null,guidance_level:f.get('guidance'),updated_at:new Date().toISOString()}).eq('id',uid);if(error)return toast(error.message);appState.profile=null;toast('Profile saved');location.reload()}
function renderCategories(box){const custom=(appState.categories||[]).filter(c=>c.owner_user_id);box.innerHTML=`<div class="settings-section-head"><span class="eyebrow">ORGANISATION</span><h2>Category library</h2><p>Categories work like folders. Create a category inside any category and keep going as deep as you need.</p><button class="button primary" id="newCategory">${icon('plus')} New category</button></div><div class="settings-card category-browser"><div class="category-browser-head"><strong>Built-in + your custom folders</strong><span>${(appState.categories||[]).length} categories</span></div><div class="category-tree">${(appState.categories||[]).map(c=>`<div class="category-tree-row"><span>${icon('folder',15)} ${esc(categoryPath(c.id))}</span>${c.owner_user_id?`<button data-delete-category="${c.id}">${icon('trash',14)}</button>`:'<small>Built-in</small>'}</div>`).join('')}</div></div>`;$('#newCategory').onclick=()=>openCategory();$$('[data-delete-category]').forEach(b=>b.onclick=()=>confirmDestructive('Delete custom category?','Items inside it become uncategorised if no deeper category remains. Custom child folders are also removed.','DELETE',async()=>{const {error}=await supabase.from('resale_categories').delete().eq('id',b.dataset.deleteCategory);if(error)throw error}))}
async function openCategory(){await loadCore();const wrap=modal(`<div class="platform-modal-head"><span class="eyebrow">NEW FOLDER</span><h2>Create category</h2></div><form id="categoryForm" class="form-stack"><label>Name<input name="name" placeholder="Prismatic Evolutions" required></label><label>Inside<select name="parent"><option value="">Top level</option>${categoryOptions('',false)}</select></label><button class="button primary">Create category</button></form>`);$('#categoryForm',wrap).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),uid=await userId();const {error}=await supabase.from('resale_categories').insert({owner_user_id:uid,parent_id:f.get('parent')||null,name:f.get('name'),scope:'all'});if(error)return toast(error.message);appState.categories=null;closeModal();toast('Category created');renderSettings()}}
function renderInterests(box){const prefIds=new Set((appState.prefs||[]).map(p=>p.category_id));box.innerHTML=`<div class="settings-section-head"><span class="eyebrow">PERSONALISATION</span><h2>Your interests</h2><p>Choose the categories you care about. FlippersAI combines these with your location, watches and activity to rank Community Intel for you.</p></div><div class="settings-card"><label>Add interest<select id="interestSelect"><option value="">Choose a category</option>${categoryOptions('',false)}</select></label><button class="button primary" id="addInterest">Add interest</button><div class="interest-list">${(appState.prefs||[]).map(p=>`<div><span>${esc(categoryPath(p.category_id))}</span><button data-remove-interest="${p.category_id}">${icon('trash',14)}</button></div>`).join('')||'<div class="platform-empty">No interests selected yet.</div>'}</div></div>`;$('#addInterest').onclick=async()=>{const id=$('#interestSelect').value;if(!id||prefIds.has(id))return;const uid=userId();const {error}=await supabase.from('profile_category_preferences').insert({user_id:await uid,category_id:id,weight:1});if(error)return toast(error.message);appState.prefs=null;renderSettings()};$$('[data-remove-interest]').forEach(b=>b.onclick=async()=>{await supabase.from('profile_category_preferences').delete().eq('category_id',b.dataset.removeInterest);appState.prefs=null;renderSettings()})}
function renderWatches(box){box.innerHTML=`<div class="settings-section-head"><span class="eyebrow">WATCHES & ALERTS</span><h2>Monitor what matters</h2><p>Replace constant Discord checking with targeted intelligence that comes to you.</p><button class="button primary" id="settingsNewWatch">${icon('plus')} Create watch</button></div><div class="watch-list">${(appState.watches||[]).map(w=>`<div class="settings-card watch-row"><div><strong>${esc(w.name)}</strong><small>${esc([w.query,w.retailer,w.location_text,w.category_id?categoryPath(w.category_id):''].filter(Boolean).join(' · ')||'Broad community watch')}</small></div><div><span class="status-badge ${w.enabled?'green':'gray'}">${w.enabled?'Active':'Paused'}</span><button data-edit-watch="${w.id}">${icon('edit',15)}</button><button data-delete-watch="${w.id}">${icon('trash',15)}</button></div></div>`).join('')||'<div class="settings-card platform-empty">No watches yet.</div>'}</div>`;$('#settingsNewWatch').onclick=()=>openWatch();$$('[data-edit-watch]').forEach(b=>b.onclick=()=>openWatch((appState.watches||[]).find(w=>w.id===b.dataset.editWatch)));$$('[data-delete-watch]').forEach(b=>b.onclick=()=>confirmDestructive('Delete watch?','Its existing alert history will also be removed.','DELETE',async()=>{const {error}=await supabase.from('community_watches').delete().eq('id',b.dataset.deleteWatch);if(error)throw error}))}
function renderData(box){box.innerHTML=`<div class="settings-section-head"><span class="eyebrow">DATA CONTROL</span><h2>Reset a section</h2><p>Useful while testing, cleaning incorrect data or starting a part of FlippersAI again.</p></div><div class="reset-grid">${[['Deals','Remove Deal Files and analyses','deals','RESET DEALS'],['Inventory','Remove inventory and item-specific records','inventory','RESET INVENTORY'],['Finances','Clear the finance ledger','finances','RESET FINANCES'],['Watches','Clear watches and alerts','watches','RESET WATCHES'],['Operational data','Clear deals, inventory, finances, saved Intel and watches','all_personal_data','RESET ALL']].map(([title,copy,key,word])=>`<div class="settings-card reset-card"><div><strong>${title}</strong><small>${copy}</small></div><button class="button secondary" data-reset-section="${key}" data-reset-word="${word}">Reset</button></div>`).join('')}</div>`;$$('[data-reset-section]').forEach(b=>b.onclick=()=>confirmDestructive(`Reset ${b.dataset.resetSection.replaceAll('_',' ')}?`,'This cannot be undone.',b.dataset.resetWord,async()=>{const {error}=await supabase.rpc('reset_user_section',{p_section:b.dataset.resetSection,p_starting_balance:0});if(error)throw error}))}

async function enhance(){
  if(!$('.topbar'))return
  try{await injectChrome();if(appState.settingsOpen)return;await enhanceDeals();await enhanceInventory();await enhanceFinance();await enhanceIntel()}catch(e){console.warn('FlippersAI platform enhancement:',e)}
}
function schedule(){clearTimeout(appState.timer);appState.timer=setTimeout(enhance,80)}
new MutationObserver(schedule).observe(document.getElementById('app'),{childList:true,subtree:true})
document.addEventListener('click',e=>{if(e.target.closest?.('[data-nav],.community-nav'))appState.settingsOpen=false},true)
schedule()
