import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4'
const supabase=createClient('https://msmpigerejpxepkylkxz.supabase.co','sb_publishable_PtTF2JaOtkV86zDg_Vf-bw_Vg0nCSpZ')
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)]
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))
const money=v=>v==null||v===''||Number.isNaN(Number(v))?'—':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(v))
const pct=v=>v==null||Number.isNaN(Number(v))?'—':`${Math.round(Number(v))}%`
let custom=null,rows=[],observerBusy=false
function a(c){return c?.analysis||{}}function rec(c){return c?.recommendation||a(c).recommendation||''}function score(c){return Math.round(Number(a(c).opportunity_score??a(c).overall_score??c?.score??0))}function auth(c){return a(c).authenticity_status||''}function verify(c){return rec(c)==='verify_first'||['uncertain','high_risk'].includes(auth(c))||a(c).authenticity_evidence_state==='missing_evidence'}
function worthwhile(c){const x=a(c);if(c.saved||x.shortlist_hidden)return false;if(!['rated','analysed'].includes(c.scan_status)&&!rec(c))return false;if(auth(c)==='likely_counterfeit')return false;const r=rec(c),s=score(c),pot=Number(x.success_potential||0);return ['strong_buy','buy','negotiate'].includes(r)||s>=65||(r==='verify_first'&&Math.max(s,pot)>=65)}
function toast(t){$('.toast')?.remove();const e=document.createElement('div');e.className='toast';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),2200)}
async function load(){const {data}=await supabase.from('scout_candidates').select('*').order('updated_at',{ascending:false}).limit(500);rows=data||[]}
function ensureNav(){if(observerBusy)return;observerBusy=true;try{for(const nav of [$('.desktop-nav'),$('.mobile-nav')].filter(Boolean)){for(const [key,label] of [['shortlist','Shortlist'],['saved','Saved']]){if(nav.querySelector(`[data-web-v086="${key}"]`))continue;const b=document.createElement('button');b.type='button';b.dataset.webV086=key;b.className=nav.classList.contains('mobile-nav')?'mobile-nav-item':'desktop-nav-item';b.innerHTML=`<span>${label}</span>`;b.onclick=e=>{e.preventDefault();e.stopPropagation();open(key)};const analyse=nav.querySelector('[data-nav="analyse"]');nav.insertBefore(b,analyse||nav.firstChild)}}}finally{observerBusy=false}}
function mark(){$$('[data-web-v086]').forEach(b=>b.classList.toggle('active',b.dataset.webV086===custom));if(custom)$$('[data-nav]').forEach(b=>b.classList.remove('active'))}
function title(c){return c.title||a(c).identified_name||'Untitled listing'}
function card(c,view){const x=a(c);return `<article class="web086-card" data-id="${esc(c.id)}"><div class="web086-tools">${view==='shortlist'?`<button data-act="save" title="Save">♡</button>`:`<span title="Saved">♥</span>`}<button data-act="remove" title="Remove">×</button></div><button class="web086-title" data-act="open">${esc(title(c))}</button><small>${esc(c.location||'Location unknown')}</small><div class="web086-metrics"><span>Score <b>${score(c)}/100</b></span><span>Ask <b>${money(c.asking_price)}</b></span><span>Resale <b>${money(x.resale_mid)}</b></span><span>Profit <b>${money(x.expected_profit)}</b></span><span>ROI <b>${pct(x.expected_roi_percent)}</b></span></div>${verify(c)?`<div class="web086-warn"><b>Verify first.</b> ${esc(x.authentication_request||'Authentication evidence is still incomplete.')}</div>`:''}<div class="web086-actions"><button data-act="analyse">Open Analyse</button>${view==='saved'?`<button data-act="deal">Open Deals</button>`:''}</div><div class="web086-notes"><input data-note placeholder="Quick note" value="${esc(x.user_notes||'')}"><input data-tags placeholder="Tags" value="${esc(Array.isArray(x.user_tags)?x.user_tags.join(', '):'')}"></div></article>`}
async function open(view){custom=view;await load();render()}
function render(){ensureNav();mark();const main=$('.content');if(!main)return;const list=custom==='shortlist'?rows.filter(worthwhile):rows.filter(c=>c.saved);main.innerHTML=`<section class="page-head"><div><span class="eyebrow">RESELLER HQ</span><h1>${custom==='shortlist'?'Shortlist':'Saved Leads'}</h1><p>${custom==='shortlist'?'Worthwhile Scout finds waiting for your decision. Saving moves them into Saved Leads.':'Your personal lead workspace across the website and extension.'}</p></div><button class="button primary" id="web086Finder">Find leads for me</button></section><div class="web086-summary"><div><span>${list.length}</span><small>${custom==='shortlist'?'active shortlist leads':'saved leads'}</small></div><div><span>${rows.filter(c=>verify(c)&&(custom==='shortlist'?worthwhile(c):c.saved)).length}</span><small>need verification</small></div></div>${list.length?`<div class="web086-grid">${list.map(c=>card(c,custom)).join('')}</div>`:`<div class="card empty-card"><h3>${custom==='shortlist'?'No shortlist leads yet':'No saved leads yet'}</h3><p>${custom==='shortlist'?'Scout will place worthwhile unsaved opportunities here.':'Save a Shortlist lead and it will move here automatically.'}</p></div>`}`;bind();$('#web086Finder').onclick=()=>finder()}
function bind(){$$('[data-id]').forEach(el=>{const c=rows.find(r=>String(r.id)===el.dataset.id);if(!c)return;$$('[data-act]',el).forEach(b=>b.onclick=()=>act(c,b.dataset.act));let timer;const save=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const analysis={...a(c),user_notes:$('[data-note]',el)?.value||'',user_tags:($('[data-tags]',el)?.value||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,8)};await supabase.from('scout_candidates').update({analysis,updated_at:new Date().toISOString()}).eq('id',c.id)},500)};$('[data-note]',el)?.addEventListener('input',save);$('[data-tags]',el)?.addEventListener('input',save)})}
async function act(c,name){if(name==='open'){if(c.source_url)window.open(c.source_url,'_blank','noopener');return}if(name==='save'){await supabase.from('scout_candidates').update({saved:true,saved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',c.id);toast('Moved to Saved Leads');return open('shortlist')}if(name==='remove'){if(custom==='saved')await supabase.from('scout_candidates').update({saved:false,saved_at:null,updated_at:new Date().toISOString()}).eq('id',c.id);else await supabase.from('scout_candidates').update({analysis:{...a(c),shortlist_hidden:true},updated_at:new Date().toISOString()}).eq('id',c.id);toast('Removed');return open(custom)}if(name==='analyse'){custom=null;const b=$('[data-nav="analyse"]');b?.click();return}if(name==='deal'){custom=null;const b=$('[data-nav="deals"]');b?.click();return}}
function finder(){const patterns=new Map();for(const c of rows.filter(c=>['rated','analysed'].includes(c.scan_status))){const x=a(c),name=[x.brand,x.model].filter(Boolean).join(' ')||x.category||c.category_label;if(!name)continue;const p=patterns.get(name)||{n:0,s:0,p:0,r:0};p.n++;p.s+=score(c);p.p+=Number(x.expected_profit||0);p.r+=Number(x.expected_roi_percent||0);patterns.set(name,p)}const ranked=[...patterns].map(([name,p])=>({name,...p,avg:p.s/p.n,profit:p.p/p.n,roi:p.r/p.n})).filter(x=>x.n>=1).sort((a,b)=>b.avg-a.avg||b.profit-a.profit).slice(0,8);const main=$('.content');main.innerHTML=`<section class="page-head"><div><span class="eyebrow">LEAD FINDER</span><h1>What should I search?</h1><p>Recommendations below use your real FlippersAI scan evidence. Live external marketplace analytics are not claimed unless an authorised feed is connected.</p></div><button class="button secondary" id="backHQ">Back</button></section>${ranked.length?`<div class="web086-finder">${ranked.map(x=>`<button data-search="${esc(x.name)}"><b>${esc(x.name)}</b><span>${Math.round(x.avg)}/100 average · ${money(x.profit)} expected profit · ${Math.round(x.roi)}% ROI</span><small>Suggested because this search pattern has produced stronger recent FlippersAI evidence.</small></button>`).join('')}</div>`:`<div class="card empty-card"><h3>Not enough evidence yet</h3><p>Run more Scout searches. FlippersAI will begin ranking the categories and models that repeatedly show stronger economics.</p></div>`}`;$('#backHQ').onclick=()=>render();$$('[data-search]').forEach(b=>b.onclick=()=>window.open(`https://www.facebook.com/marketplace/search/?query=${encodeURIComponent(b.dataset.search)}`,'_blank','noopener'))}
function boot(){const app=$('#app');if(!app)return;const obs=new MutationObserver(()=>{if(!custom)ensureNav()});obs.observe(app,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest?.('[data-nav]'))custom=null},true);ensureNav()}
boot()
