import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import OpenAI from 'npm:openai'

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Content-Type':'application/json'}
const schema={type:'object',additionalProperties:false,properties:{
 id:{type:'string'},identified_name:{type:'string'},category:{type:'string'},identification_confidence:{type:'number',minimum:0,maximum:100},
 resale_low:{type:['number','null']},resale_mid:{type:['number','null']},resale_high:{type:['number','null']},expected_profit:{type:['number','null']},expected_roi_percent:{type:['number','null']},resale_evidence_count:{type:'integer',minimum:0},resale_evidence_quality:{type:'string',enum:['high','medium','low','insufficient']},resale_basis:{type:'string'},
 authenticity_status:{type:'string',enum:['not_applicable','likely_genuine','uncertain','high_risk','likely_counterfeit']},authenticity_risk:{type:'number',minimum:0,maximum:100},authenticity_reasons:{type:'array',items:{type:'string'}},
 authenticity_evidence_state:{type:'string',enum:['not_applicable','strong_evidence','partial_evidence','missing_evidence','conflicting_evidence']},authenticity_evidence_seen:{type:'array',items:{type:'string'}},missing_authenticity_evidence:{type:'array',items:{type:'string'}},authentication_request:{type:'string'},
 opportunity_score:{type:'number',minimum:0,maximum:100},success_potential:{type:'number',minimum:0,maximum:100},community_confidence:{type:['number','null'],minimum:0,maximum:100},overall_score:{type:'number',minimum:0,maximum:100},overall_risk:{type:'number',minimum:0,maximum:100},recommendation:{type:'string',enum:['strong_buy','buy','negotiate','verify_first','skip']},action_summary:{type:'string'},reasons:{type:'array',items:{type:'string'}}
},required:['id','identified_name','category','identification_confidence','resale_low','resale_mid','resale_high','expected_profit','expected_roi_percent','resale_evidence_count','resale_evidence_quality','resale_basis','authenticity_status','authenticity_risk','authenticity_reasons','authenticity_evidence_state','authenticity_evidence_seen','missing_authenticity_evidence','authentication_request','opportunity_score','success_potential','community_confidence','overall_score','overall_risk','recommendation','action_summary','reasons']}
const clean=(v:unknown,max=2400)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,max)
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null}

Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors})
 if(req.method!=='POST')return new Response(JSON.stringify({error:'POST required'}),{status:405,headers:cors})
 try{
  const key=Deno.env.get('OPENAI_API_KEY');if(!key)return new Response(JSON.stringify({error:'AI service is unavailable'}),{status:503,headers:cors})
  const body=await req.json().catch(()=>({})),item=body?.item&&typeof body.item==='object'?body.item:null
  if(!item?.id)return new Response(JSON.stringify({error:'item required'}),{status:400,headers:cors})
  const compact={id:clean(item.id,100),title:clean(item.title,320),asking_price:num(item.asking_price),location:clean(item.location,160),category:clean(item.category||'Other',100),visible_text:clean(item.visible_text,2200),user_evidence:clean(body?.user_evidence||item.user_evidence,1200)}
  const prompt=`You are FlippersAI Scout's FAST FIRST PASS for one Australian resale listing. The score is an OPPORTUNITY TRIAGE score: how worthwhile this listing is to investigate further, not a claim that the item is safe to buy now.\n\nLISTING: ${JSON.stringify(compact)}\n\nRules:\n1. This is a search-card screen. Do not perform web research. resale values/profit/ROI must be null; sold evidence count 0; evidence quality insufficient.\n2. Crucial distinction: MISSING AUTHENTICATION EVIDENCE IS NOT COUNTERFEIT EVIDENCE. If a counterfeit-prone item simply does not show labels/tags/SKU/serial/receipt/close-ups in the available card evidence, use authenticity_status=uncertain and authenticity_evidence_state=missing_evidence or partial_evidence. Do NOT call it high_risk or likely_counterfeit just because evidence is absent.\n3. Use high_risk/likely_counterfeit only for positive suspicious/conflicting evidence: impossible SKU/model mismatch, clearly inconsistent branding/construction, explicit replica wording, contradictory evidence, or similarly concrete red flags. Price alone never proves fake.\n4. opportunity_score asks: if the missing facts check out, how attractive is this opportunity based on product desirability/liquidity, asking-price plausibility, apparent condition and specificity? Missing labels must reduce confidence/decision readiness, not automatically destroy opportunity_score.\n5. overall_score should closely represent opportunity_score for a promising item even when verification is missing. In that case recommendation MUST be verify_first and action_summary must say not to buy until verified.\n6. For counterfeit-prone items, state exactly what evidence is visible, what is missing, and write authentication_request as a short natural seller message asking for the specific photos/evidence required. If authentication is not applicable, use empty arrays/message.\n7. strong_buy/buy should almost never occur at this first pass because live comps are absent. verify_first is appropriate for promising opportunities with answerable uncertainty.\n8. Genuine poor opportunities still score low. Do not inflate weak, generic, damaged, implausible or low-demand listings just to create green results.\n9. User evidence is additional evidence, not truth by declaration. Consider it, but do not mark genuine solely because the user says so.\n10. Keep reasons concise and decision-useful. Currency is AUD. Never fabricate facts.`
  const client=new OpenAI({apiKey:key,maxRetries:0,timeout:35000})
  const response=await client.responses.create({model:'gpt-5-mini',input:[{role:'user',content:[{type:'input_text',text:prompt}]}],text:{format:{type:'json_schema',name:'scout_quick_rating_v3',strict:true,schema}},store:false})
  if(!response.output_text)throw new Error('No Scout quick rating returned')
  const result=JSON.parse(response.output_text);result.id=compact.id;result.resale_low=null;result.resale_mid=null;result.resale_high=null;result.expected_profit=null;result.expected_roi_percent=null;result.resale_evidence_count=0;result.resale_evidence_quality='insufficient';result.community_confidence=null
  const missing=['missing_evidence','partial_evidence'].includes(result.authenticity_evidence_state)
  if(result.authenticity_status==='likely_counterfeit'||result.authenticity_evidence_state==='conflicting_evidence'&&result.authenticity_status==='high_risk'){
    result.recommendation='skip';result.overall_score=Math.min(Number(result.overall_score||0),20);result.success_potential=Math.min(Number(result.success_potential||0),20)
  }else if(result.authenticity_status==='high_risk'&&!missing){
    result.recommendation='verify_first';result.overall_score=Math.min(Number(result.overall_score||0),55)
  }else if(missing&&result.opportunity_score>=60){
    result.recommendation='verify_first';result.overall_score=Math.max(Number(result.overall_score||0),Number(result.opportunity_score||0))
  }else if(['strong_buy','buy'].includes(result.recommendation))result.recommendation='verify_first'
  return new Response(JSON.stringify({result,engine_version:'flippers-scout-quick-3-evidence-aware-timeout-fix'}),{headers:cors})
 }catch(err){console.error('scout_quick_rate_failed',err);return new Response(JSON.stringify({error:err instanceof Error?err.message:String(err)}),{status:500,headers:cors})}
})