import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import OpenAI from 'npm:openai'

const cors={
  'Access-Control-Allow-Origin':'*',
  'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods':'POST, OPTIONS',
  'Content-Type':'application/json'
}
const clean=(v:unknown,max=12000)=>String(v??'').trim().slice(0,max)
const num=(v:unknown)=>{if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null}
const uniq=<T>(x:T[])=>[...new Set(x)]
function decode(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
function platformFromUrl(url:URL){const h=url.hostname.toLowerCase();if(h.includes('depop.'))return'depop';if(h.includes('ebay.'))return'ebay';if(h.includes('facebook.'))return'facebook';if(h.includes('gumtree.'))return'gumtree';return'other'}
function listingIdFromUrl(url:URL,p:string){const path=url.pathname.replace(/\/+$/,'');if(p==='depop')return path.match(/\/products\/([^/]+)/i)?.[1]||'';if(p==='ebay')return path.match(/\/(?:itm\/)?(?:[^/]+\/)?(\d{9,})/i)?.[1]||'';return path.split('/').filter(Boolean).at(-1)||''}
function attr(html:string,name:string){const e=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const p of [new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']+)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${e}["']`,'i')]){const m=html.match(p);if(m?.[1])return decode(m[1])}return''}
function parseJsonLd(html:string){const blocks:any[]=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{const p=JSON.parse(m[1].trim());Array.isArray(p)?blocks.push(...p):blocks.push(p)}catch{}}return blocks}
function flatten(nodes:any[]){const out:any[]=[];const walk=(x:any)=>{if(!x||typeof x!=='object')return;if(Array.isArray(x)){x.forEach(walk);return}out.push(x);if(x['@graph'])walk(x['@graph']);if(x.itemListElement)walk(x.itemListElement)};nodes.forEach(walk);return out}
function productOf(nodes:any[]){return flatten(nodes).find(x=>{const t=x?.['@type'];return t==='Product'||(Array.isArray(t)&&t.includes('Product'))})||null}
function offerOf(p:any){const o=p?.offers;return Array.isArray(o)?o.find(Boolean)||null:(o&&typeof o==='object'?o:null)}
function sellerOf(p:any,o:any){const s=o?.seller||p?.seller;if(typeof s==='string')return s;return clean(s?.name||s?.alternateName||'',300)}
function conditionOf(p:any,o:any){const raw=clean(o?.itemCondition||p?.itemCondition||'',500);if(!raw)return'';return (raw.split('/').filter(Boolean).at(-1)||raw).replace(/Condition$/i,'').replace(/([a-z])([A-Z])/g,'$1 $2').trim()}
function imageList(p:any,html:string){const vals:string[]=[];const add=(v:any)=>{if(typeof v==='string'&&/^https?:\/\//i.test(v))vals.push(v);else if(v&&typeof v==='object')add(v.url||v.contentUrl)};Array.isArray(p?.image)?p.image.forEach(add):add(p?.image);add(attr(html,'og:image'));add(attr(html,'twitter:image'));return uniq(vals).slice(0,12)}
async function fetchPage(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{return await fetch(url,{redirect:'follow',signal:c.signal,headers:{'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/131 Safari/537.36','accept':'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','accept-language':'en-AU,en;q=0.9'}})}finally{clearTimeout(t)}}

const searchSchema={type:'object',additionalProperties:false,properties:{listing_title:{type:'string'},description:{type:'string'},asking_price:{type:['number','null']},currency:{type:'string'},seller_name:{type:'string'},listing_location:{type:'string'},condition:{type:'string'},size:{type:'string'},image_urls:{type:'array',items:{type:'string'}},source_urls:{type:'array',items:{type:'string'}},confidence:{type:'number',minimum:0,maximum:1}},required:['listing_title','description','asking_price','currency','seller_name','listing_location','condition','size','image_urls','source_urls','confidence']}
async function indexedFallback(url:string,platform:string,listingId:string){const key=Deno.env.get('OPENAI_API_KEY');if(!key)return null;const client=new OpenAI({apiKey:key,maxRetries:0,timeout:35000});const prompt=`You are FlippersAI's factual listing-retrieval fallback. The direct marketplace page could not be fully parsed. Use web search to find the EXACT listing below in search indexes/caches/public indexed representations. Do not substitute a different listing. Exact URL: ${url}\nPlatform: ${platform}\nListing ID/slug: ${listingId}\nReturn only facts that can be tied to this exact listing: title, seller asking price, currency, seller username/name, location, condition, size, description, and direct listing image URLs if visible. source_urls must contain real URLs that support the facts. If a field cannot be verified, leave string empty or price null. Confidence is overall confidence that the returned facts belong to this exact listing.`;try{const r=await client.responses.create({model:'gpt-5-mini',tools:[{type:'web_search',user_location:{type:'approximate',country:'AU',city:'Melbourne',region:'Victoria',timezone:'Australia/Melbourne'}}],input:[{role:'user',content:[{type:'input_text',text:prompt}]}],text:{format:{type:'json_schema',name:'indexed_listing_facts',strict:true,schema:searchSchema}},store:false},{timeout:35000,maxRetries:0});if(!r.output_text)return null;return JSON.parse(r.output_text)}catch(e){console.error('indexed_fallback_failed',clean(e instanceof Error?e.message:String(e),500));return null}}

Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'POST required'}),{status:405,headers:cors});const diagnosticId=crypto.randomUUID();
 try{const body=await req.json(),raw=clean(body?.listing_url,4000);if(!raw)return new Response(JSON.stringify({error:'listing_url is required'}),{status:400,headers:cors});let u:URL;try{u=new URL(raw)}catch{return new Response(JSON.stringify({error:'Invalid listing URL'}),{status:400,headers:cors})};const platform=platformFromUrl(u),listingId=listingIdFromUrl(u,platform),started=Date.now();let direct:any={};let directStatus='not_attempted',httpStatus=null;
  try{const r=await fetchPage(u.toString());httpStatus=r.status;const ct=r.headers.get('content-type')||'',html=(ct.includes('text')||ct.includes('html'))?await r.text():'';if(r.ok&&html){const ld=parseJsonLd(html),p=productOf(ld),o=offerOf(p),title=clean(p?.name||attr(html,'og:title')||attr(html,'twitter:title')||decode(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g,' ').trim()||''),500),description=clean(p?.description||attr(html,'og:description')||attr(html,'description'),12000),price=num(o?.price??o?.lowPrice??attr(html,'product:price:amount'));direct={listing_title:title,description,asking_price:price,currency:clean(o?.priceCurrency||attr(html,'product:price:currency')||'AUD',12).toUpperCase(),seller_name:sellerOf(p,o),listing_location:clean(o?.availableAtOrFrom?.address?.addressLocality||o?.areaServed?.name||'',200),condition:conditionOf(p,o),size:'',image_urls:imageList(p,html)};directStatus='parsed'}else directStatus=r.status===401||r.status===403?'blocked':'http_error'}catch(e){directStatus='fetch_failed';console.error('listing_direct_failed',{diagnosticId,detail:clean(e instanceof Error?e.message:String(e),500)})}
  const directUseful=Boolean(direct.listing_title&&(direct.asking_price!==null||direct.seller_name||direct.condition||direct.description||direct.image_urls?.length));let indexed:any=null;if(!directUseful||direct.asking_price===null||!direct.seller_name||!direct.condition){indexed=await indexedFallback(u.toString(),platform,listingId)}
  const choose=(a:any,b:any)=>a!==null&&a!==undefined&&a!==''&&(Array.isArray(a)?a.length>0:true)?a:b;const facts={source_platform:platform,listing_id:listingId,listing_url:u.toString(),listing_title:choose(direct.listing_title,indexed?.listing_title)||'',description:choose(direct.description,indexed?.description)||'',asking_price:direct.asking_price!==null&&direct.asking_price!==undefined?direct.asking_price:(indexed?.asking_price??null),currency:choose(direct.currency,indexed?.currency)||'AUD',asking_price_verified:(direct.asking_price!==null&&direct.asking_price!==undefined)||Boolean(indexed?.asking_price!==null&&indexed?.asking_price!==undefined&&indexed?.confidence>=0.75),asking_price_confidence:direct.asking_price!==null&&direct.asking_price!==undefined?0.98:Number(indexed?.asking_price!==null&&indexed?.asking_price!==undefined?indexed?.confidence||0:0),seller_name:choose(direct.seller_name,indexed?.seller_name)||'',listing_location:choose(direct.listing_location,indexed?.listing_location)||'',condition:choose(direct.condition,indexed?.condition)||'',size:choose(direct.size,indexed?.size)||'',image_urls:uniq([...(direct.image_urls||[]),...(indexed?.image_urls||[])]).slice(0,12),source_http_status:httpStatus};const missing=['listing_title','asking_price','seller_name','condition','image_urls'].filter(k=>{const v=(facts as any)[k];return v===null||v===''||(Array.isArray(v)&&!v.length)});const provenance:any={};for(const k of Object.keys(facts)){if(k in direct&&choose(direct[k],null)!==null&&choose(direct[k],null)!=='')provenance[k]='direct_page';else if(indexed&&k in indexed&&choose(indexed[k],null)!==null&&choose(indexed[k],null)!=='')provenance[k]='indexed_web_search'}
  return new Response(JSON.stringify({acquired:true,acquisition_status:missing.length?'partial':'complete',diagnostic_id:diagnosticId,duration_ms:Date.now()-started,facts,provenance,missing_fields:missing,direct_status:directStatus,indexed_fallback_used:Boolean(indexed),indexed_source_urls:indexed?.source_urls||[],engine_version:'listing-acquisition-alpha-2'}),{headers:cors})
 }catch(e){return new Response(JSON.stringify({error:'Listing acquisition failed',diagnostic_id:diagnosticId,detail:clean(e instanceof Error?e.message:String(e),700)}),{status:500,headers:cors})}
})